In [2]:
import polars as pl
import pyarrow.parquet as pq
import sys

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.preprocessing import OneHotEncoder

filepath = "../Data/processed/sirene_infos.parquet" 

print("--- Début de la lecture 'bypass' ---")

try:
    print(f"Lecture du fichier via PyArrow : {filepath}")
    table_arrow = pq.read_table(
        filepath,
    )
    
    print("Conversion de la table PyArrow en DataFrame Polars...")
    df_demo = pl.from_arrow(table_arrow)
    
    print("--- SUCCÈS ! ---\n")
    print("Le DataFrame est maintenant dans Polars, prêt pour la transformation.")
    print(df_demo.head())

except Exception as e:
    print(f"\n--- ERREUR ---", file=sys.stderr)
    print(f"Impossible de lire le fichier, même avec PyArrow : {e}", file=sys.stderr)

--- Début de la lecture 'bypass' ---
Lecture du fichier via PyArrow : ../Data/processed/sirene_infos.parquet
Conversion de la table PyArrow en DataFrame Polars...
--- SUCCÈS ! ---

Le DataFrame est maintenant dans Polars, prêt pour la transformation.
shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ dateCreat ┆ dateFerme ┆ is_failed ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ionUniteL ┆ ture      ┆ _in_3y    ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ egale     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆ ---       ┆ date      ┆ i32       ┆   ┆ i8        ┆ str       ┆ ---       ┆ ---      │
│           ┆ date      ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000325175 ┆ 2000-09-2 ┆ null      ┆ 0         ┆ … ┆ 9         ┆ 13        ┆ NN        ┆ N        │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005540273 ┆ 1972-01-0 ┆ null      ┆ 0         ┆ … ┆ 1         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005541552 ┆ 1974-01-0 ┆ null      ┆ 0         ┆ … ┆ 1         ┆ 04        ┆ 01        ┆ O        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005641154 ┆ 1981-02-0 ┆ null      ┆ 0         ┆ … ┆ 2         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005742580 ┆ 1993-03-0 ┆ null      ┆ 0         ┆ … ┆ 3         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
df_demo.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 10223433  ┆ 10223433  ┆ 432318    ┆ … ┆ 1.0223433 ┆ 10223433  ┆ 10223433  ┆ 10223433 │
│           ┆           ┆           ┆           ┆   ┆ e7        ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 9791115   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2012-06-0 ┆ 2018-11-3 ┆ … ┆ 6.185161  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 8 22:07:5 ┆ 0 19:07:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 7.438449  ┆ 1.502921  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.593599  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 000325175 ┆ 1970-01-0 ┆ 1971-04-1 ┆ … ┆ 1.0       ┆  D        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2007-05-1 ┆ 2017-01-0 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 0         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2016-02-0 ┆ 2020-12-3 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2021-02-1 ┆ 2022-12-3 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-11-0 ┆ 2025-11-1 ┆ … ┆ 12.0      ┆ sw        ┆ NN        ┆ O        │
│           ┆           ┆ 1         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
import re

df_demo = df_demo.filter(df_demo['departement'].str.contains(r'^\d+$'))
print(df_demo)

shape: (8_812_287, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ dateCreat ┆ dateFerme ┆ is_failed ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ionUniteL ┆ ture      ┆ _in_3y    ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ egale     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆ ---       ┆ date      ┆ i32       ┆   ┆ i8        ┆ str       ┆ ---       ┆ ---      │
│           ┆ date      ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000325175 ┆ 2000-09-2 ┆ null      ┆ 0         ┆ … ┆ 9         ┆ 13        ┆ NN        ┆ N        │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005540273 ┆ 1972-01-0 ┆ null      ┆ 0         ┆ … ┆ 1         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005541552 ┆ 1974-01-0 ┆ null      ┆ 0         ┆ … ┆ 1         ┆ 04        ┆ 01        ┆ O        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005641154 ┆ 1981-02-0 ┆ null      ┆ 0         ┆ … ┆ 2         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005742580 ┆ 1993-03-0 ┆ null      ┆ 0         ┆ … ┆ 3         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 999990369 ┆ 1981-04-2 ┆ null      ┆ 0         ┆ … ┆ 4         ┆ 92        ┆ 21        ┆ O        │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999990401 ┆ 1981-06-0 ┆ null      ┆ 0         ┆ … ┆ 6         ┆ 44        ┆ 11        ┆ O        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999990443 ┆ 1982-04-0 ┆ null      ┆ 0         ┆ … ┆ 4         ┆ 75        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999990666 ┆ 1986-05-1 ┆ null      ┆ 0         ┆ … ┆ 5         ┆ 75        ┆ NN        ┆ N        │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999992357 ┆ 2003-12-3 ┆ null      ┆ 0         ┆ … ┆ 12        ┆ 80        ┆ 01        ┆ O        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df_demo.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 8812287   ┆ 8812287   ┆ 336384    ┆ … ┆ 8.812287e ┆ 8812287   ┆ 8812287   ┆ 8812287  │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 8475903   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2011-10-2 ┆ 2018-03-2 ┆ … ┆ 6.160596  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 0 20:14:2 ┆ 5 19:50:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 0.123597  ┆ 4.452054  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.604019  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 000325175 ┆ 1970-01-0 ┆ 1971-04-1 ┆ … ┆ 1.0       ┆ 00        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2006-04-2 ┆ 2015-11-1 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2015-04-0 ┆ 2020-05-1 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2020-11-1 ┆ 2022-08-3 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 9         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-11-0 ┆ 2025-10-3 ┆ … ┆ 12.0      ┆ 99        ┆ NN        ┆ O        │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
# Supprime moi toutes les lignes NN de la colonne trancheEffectifsSiege

df_demo = df_demo.filter(df_demo['trancheEffectifsSiege'] != 'NN')

In [7]:
df_demo.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1521228   ┆ 1521228   ┆ 16212     ┆ … ┆ 1.521228e ┆ 1521228   ┆ 1521228   ┆ 1521228  │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 1505016   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2008-05-2 ┆ 2016-06-2 ┆ … ┆ 5.988167  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 2 03:59:5 ┆ 1 07:40:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 2.218918  ┆ 4.182087  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.674555  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 005541552 ┆ 1970-01-0 ┆ 1983-02-2 ┆ … ┆ 1.0       ┆ 01        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2000-03-0 ┆ 2012-03-2 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2012-01-0 ┆ 2019-01-0 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2018-11-0 ┆ 2022-09-0 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 3         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-06-1 ┆ 2025-10-2 ┆ … ┆ 12.0      ┆ 97        ┆ 53        ┆ O        │
│           ┆           ┆ 3         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
# Affiche moi toutes les valeurs uniques de trancheEffectifsUniteLegale

print(df_demo['trancheEffectifsUniteLegale'].unique())

shape: (16,)
Series: 'trancheEffectifsUniteLegale' [str]
[
	"52"
	"31"
	"22"
	"41"
	"01"
	…
	"11"
	"21"
	"51"
	"42"
	"NN"
]

In [9]:
# Supprime toutes les lignes NN de la colonne trancheEffectifsUniteLegale

df_demo = df_demo.filter(df_demo['trancheEffectifsUniteLegale'] != 'NN')

In [10]:
df_demo.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1521227   ┆ 1521227   ┆ 16212     ┆ … ┆ 1.521227e ┆ 1521227   ┆ 1521227   ┆ 1521227  │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 1505015   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2008-05-2 ┆ 2016-06-2 ┆ … ┆ 5.988163  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 2 04:04:1 ┆ 1 07:40:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 0.992126  ┆ 4.182087  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.674553  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 005541552 ┆ 1970-01-0 ┆ 1983-02-2 ┆ … ┆ 1.0       ┆ 01        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2000-03-0 ┆ 2012-03-2 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2012-01-0 ┆ 2019-01-0 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2018-11-0 ┆ 2022-09-0 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 3         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-06-1 ┆ 2025-10-2 ┆ … ┆ 12.0      ┆ 97        ┆ 53        ┆ O        │
│           ┆           ┆ 3         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
# Supprime les colonnes societeMissionUniteLegale et economieSocialeSolidaireUniteLegale

df_demo = df_demo.drop(['societeMissionUniteLegale', 'economieSocialeSolidaireUniteLegale'])
df_demo.describe()

shape: (9, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1521227   ┆ 1521227   ┆ 16212     ┆ … ┆ 1.521227e ┆ 1521227   ┆ 1521227   ┆ 1521227  │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 1505015   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2008-05-2 ┆ 2016-06-2 ┆ … ┆ 5.988163  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 2 04:04:1 ┆ 1 07:40:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 0.992126  ┆ 4.182087  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.674553  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 005541552 ┆ 1970-01-0 ┆ 1983-02-2 ┆ … ┆ 1.0       ┆ 01        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2000-03-0 ┆ 2012-03-2 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2012-01-0 ┆ 2019-01-0 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2018-11-0 ┆ 2022-09-0 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 3         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-06-1 ┆ 2025-10-2 ┆ … ┆ 12.0      ┆ 97        ┆ 53        ┆ O        │
│           ┆           ┆ 3         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

---

In [12]:
import polars as pl
import pyarrow.parquet as pq
import sys

filepath = "../Data/processed/sirene_bilan.parquet" 

print("--- Début de la lecture 'bypass' ---")

try:
    print(f"Lecture du fichier via PyArrow : {filepath}")
    table_arrow = pq.read_table(
        filepath,
    )
    
    print("Conversion de la table PyArrow en DataFrame Polars...")
    df_bilan = pl.from_arrow(table_arrow)
    
    print("--- SUCCÈS ! ---\n")
    print("Le DataFrame est maintenant dans Polars, prêt pour la transformation.")
    print(df_bilan.head())

except Exception as e:
    print(f"\n--- ERREUR ---", file=sys.stderr)
    print(f"Impossible de lire le fichier, même avec PyArrow : {e}", file=sys.stderr)

--- Début de la lecture 'bypass' ---
Lecture du fichier via PyArrow : ../Data/processed/sirene_bilan.parquet
Conversion de la table PyArrow en DataFrame Polars...
--- SUCCÈS ! ---

Le DataFrame est maintenant dans Polars, prêt pour la transformation.
shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ date_clot ┆ EG_Impots ┆ FA_Chiffr ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ ure_exerc ┆ Taxes     ┆ eAffaires ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ ice       ┆ ---       ┆ Ventes    ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆ ---       ┆ i32       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆ date      ┆           ┆ i32       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 005420120 ┆ 2018-12-3 ┆ 841098    ┆ 4623      ┆ … ┆ 0.0       ┆ 0.047087  ┆ 29.374216 ┆ 101.8593 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 99       │
│ 005420120 ┆ 2021-12-3 ┆ 2500000   ┆ 44073     ┆ … ┆ 0.0       ┆ 0.065831  ┆ 6.162617  ┆ 14.06566 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005420120 ┆ 2017-12-3 ┆ 441247    ┆ 26192     ┆ … ┆ 0.0       ┆ 0.03138   ┆ 3.745877  ┆ 17.20460 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005420120 ┆ 2016-12-3 ┆ 586967    ┆ 11836     ┆ … ┆ 0.0       ┆ 0.022292  ┆ 8.805762  ┆ 66.05635 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 005420120 ┆ 2019-12-3 ┆ 0         ┆ 48370     ┆ … ┆ 0.0       ┆ 0.05589   ┆ 4.502626  ┆ 10.75797 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
df_bilan.describe()

shape: (9, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ date_clot ┆ EG_Impots ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ ---       ┆ ure_exerc ┆ Taxes     ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ str       ┆ ice       ┆ ---       ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆           ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆           ┆ str       ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3706645   ┆ 3706645   ┆ 3.706645e ┆ … ┆ 3.706645e ┆ 3.706645e ┆ 3.706645e ┆ 3.706645 │
│           ┆           ┆           ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2019-10-0 ┆ 1.1025e6  ┆ … ┆ 8.7383e8  ┆ 2.1672e11 ┆ 1.1745e12 ┆ 3.0131e1 │
│           ┆           ┆ 6 17:39:4 ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│           ┆           ┆ 9.194433  ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ 1.6389e7  ┆ … ┆ 1.1443e12 ┆ 1.7773e13 ┆ 1.6774e13 ┆ 5.1192e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ min       ┆ 005420120 ┆ 1919-09-3 ┆ -2.1475e9 ┆ … ┆ -7.2972e1 ┆ -2.1475e1 ┆ -2.1460e1 ┆ -2.1475e │
│           ┆           ┆ 0         ┆           ┆   ┆ 2         ┆ 5         ┆ 5         ┆ 15       │
│ 25%       ┆ null      ┆ 2017-12-3 ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.024045  ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2019-12-3 ┆ 82447.0   ┆ … ┆ 0.0       ┆ 0.084052  ┆ 1.003174  ┆ 60.75291 │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ 75%       ┆ null      ┆ 2021-09-3 ┆ 431133.0  ┆ … ┆ 0.0       ┆ 0.332404  ┆ 1.3592e11 ┆ 3.7060e1 │
│           ┆           ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ max       ┆ 999990542 ┆ 2029-12-3 ┆ 2.1475e9  ┆ … ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e1 │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘