# DEBUT TRANSFORMATION DEMO

In [1]:
import polars as pl
import pyarrow.parquet as pq
import sys

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.preprocessing import OneHotEncoder

filepath = "../Data/processed/sirene_infos.parquet" 

print("--- Début de la lecture 'bypass' ---")

try:
    print(f"Lecture du fichier via PyArrow : {filepath}")
    table_arrow = pq.read_table(
        filepath,
    )
    
    print("Conversion de la table PyArrow en DataFrame Polars...")
    df_demo = pl.from_arrow(table_arrow)
    
    print("--- SUCCÈS ! ---\n")
    print("Le DataFrame est maintenant dans Polars, prêt pour la transformation.")
    print(df_demo.head())

except Exception as e:
    print(f"\n--- ERREUR ---", file=sys.stderr)
    print(f"Impossible de lire le fichier, même avec PyArrow : {e}", file=sys.stderr)

--- Début de la lecture 'bypass' ---
Lecture du fichier via PyArrow : ../Data/processed/sirene_infos.parquet
Conversion de la table PyArrow en DataFrame Polars...
--- SUCCÈS ! ---

Le DataFrame est maintenant dans Polars, prêt pour la transformation.
shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ dateCreat ┆ dateFerme ┆ is_failed ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ionUniteL ┆ ture      ┆ _in_3y    ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ egale     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆ ---       ┆ date      ┆ i32       ┆   ┆ i8        ┆ str       ┆ ---       ┆ ---      │
│           ┆ date      ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000325175 ┆ 2000-09-2 ┆ null      ┆ 0         ┆ … ┆ 9         ┆ 13        ┆ NN        ┆ N        │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005540273 ┆ 1972-01-0 ┆ null      ┆ 0         ┆ … ┆ 1         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005541552 ┆ 1974-01-0 ┆ null      ┆ 0         ┆ … ┆ 1         ┆ 04        ┆ 01        ┆ O        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005641154 ┆ 1981-02-0 ┆ null      ┆ 0         ┆ … ┆ 2         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005742580 ┆ 1993-03-0 ┆ null      ┆ 0         ┆ … ┆ 3         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [2]:
df_demo.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 10223433  ┆ 10223433  ┆ 432318    ┆ … ┆ 1.0223433 ┆ 10223433  ┆ 10223433  ┆ 10223433 │
│           ┆           ┆           ┆           ┆   ┆ e7        ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 9791115   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2012-06-0 ┆ 2018-11-3 ┆ … ┆ 6.185161  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 8 22:07:5 ┆ 0 19:07:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 7.438449  ┆ 1.502921  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.593599  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 000325175 ┆ 1970-01-0 ┆ 1971-04-1 ┆ … ┆ 1.0       ┆  D        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2007-05-1 ┆ 2017-01-0 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 0         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2016-02-0 ┆ 2020-12-3 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2021-02-1 ┆ 2022-12-3 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-11-0 ┆ 2025-11-1 ┆ … ┆ 12.0      ┆ sw        ┆ NN        ┆ O        │
│           ┆           ┆ 1         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
import re

df_demo = df_demo.filter(df_demo['departement'].str.contains(r'^\d+$'))
print(df_demo)

shape: (8_812_287, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ dateCreat ┆ dateFerme ┆ is_failed ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ionUniteL ┆ ture      ┆ _in_3y    ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ egale     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆ ---       ┆ date      ┆ i32       ┆   ┆ i8        ┆ str       ┆ ---       ┆ ---      │
│           ┆ date      ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000325175 ┆ 2000-09-2 ┆ null      ┆ 0         ┆ … ┆ 9         ┆ 13        ┆ NN        ┆ N        │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005540273 ┆ 1972-01-0 ┆ null      ┆ 0         ┆ … ┆ 1         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005541552 ┆ 1974-01-0 ┆ null      ┆ 0         ┆ … ┆ 1         ┆ 04        ┆ 01        ┆ O        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005641154 ┆ 1981-02-0 ┆ null      ┆ 0         ┆ … ┆ 2         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 005742580 ┆ 1993-03-0 ┆ null      ┆ 0         ┆ … ┆ 3         ┆ 04        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 999990369 ┆ 1981-04-2 ┆ null      ┆ 0         ┆ … ┆ 4         ┆ 92        ┆ 21        ┆ O        │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999990401 ┆ 1981-06-0 ┆ null      ┆ 0         ┆ … ┆ 6         ┆ 44        ┆ 11        ┆ O        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999990443 ┆ 1982-04-0 ┆ null      ┆ 0         ┆ … ┆ 4         ┆ 75        ┆ NN        ┆ N        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999990666 ┆ 1986-05-1 ┆ null      ┆ 0         ┆ … ┆ 5         ┆ 75        ┆ NN        ┆ N        │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999992357 ┆ 2003-12-3 ┆ null      ┆ 0         ┆ … ┆ 12        ┆ 80        ┆ 01        ┆ O        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
df_demo.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 8812287   ┆ 8812287   ┆ 336384    ┆ … ┆ 8.812287e ┆ 8812287   ┆ 8812287   ┆ 8812287  │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 8475903   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2011-10-2 ┆ 2018-03-2 ┆ … ┆ 6.160596  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 0 20:14:2 ┆ 5 19:50:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 0.123597  ┆ 4.452054  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.604019  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 000325175 ┆ 1970-01-0 ┆ 1971-04-1 ┆ … ┆ 1.0       ┆ 00        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2006-04-2 ┆ 2015-11-1 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2015-04-0 ┆ 2020-05-1 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2020-11-1 ┆ 2022-08-3 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 9         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-11-0 ┆ 2025-10-3 ┆ … ┆ 12.0      ┆ 99        ┆ NN        ┆ O        │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# Supprime moi toutes les lignes NN de la colonne trancheEffectifsSiege

df_demo = df_demo.filter(df_demo['trancheEffectifsSiege'] != 'NN')

In [6]:
df_demo.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1521228   ┆ 1521228   ┆ 16212     ┆ … ┆ 1.521228e ┆ 1521228   ┆ 1521228   ┆ 1521228  │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 1505016   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2008-05-2 ┆ 2016-06-2 ┆ … ┆ 5.988167  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 2 03:59:5 ┆ 1 07:40:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 2.218918  ┆ 4.182087  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.674555  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 005541552 ┆ 1970-01-0 ┆ 1983-02-2 ┆ … ┆ 1.0       ┆ 01        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2000-03-0 ┆ 2012-03-2 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2012-01-0 ┆ 2019-01-0 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2018-11-0 ┆ 2022-09-0 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 3         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-06-1 ┆ 2025-10-2 ┆ … ┆ 12.0      ┆ 97        ┆ 53        ┆ O        │
│           ┆           ┆ 3         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
# Affiche moi toutes les valeurs uniques de trancheEffectifsUniteLegale

print(df_demo['trancheEffectifsUniteLegale'].unique())

shape: (16,)
Series: 'trancheEffectifsUniteLegale' [str]
[
	"02"
	"11"
	"03"
	"22"
	"00"
	…
	"01"
	"53"
	"42"
	"32"
	"51"
]

In [8]:
# Supprime toutes les lignes NN de la colonne trancheEffectifsUniteLegale

df_demo = df_demo.filter(df_demo['trancheEffectifsUniteLegale'] != 'NN')

In [9]:
df_demo.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1521227   ┆ 1521227   ┆ 16212     ┆ … ┆ 1.521227e ┆ 1521227   ┆ 1521227   ┆ 1521227  │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 1505015   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2008-05-2 ┆ 2016-06-2 ┆ … ┆ 5.988163  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 2 04:04:1 ┆ 1 07:40:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 0.992126  ┆ 4.182087  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.674553  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 005541552 ┆ 1970-01-0 ┆ 1983-02-2 ┆ … ┆ 1.0       ┆ 01        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2000-03-0 ┆ 2012-03-2 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2012-01-0 ┆ 2019-01-0 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2018-11-0 ┆ 2022-09-0 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 3         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-06-1 ┆ 2025-10-2 ┆ … ┆ 12.0      ┆ 97        ┆ 53        ┆ O        │
│           ┆           ┆ 3         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
# Supprime les colonnes societeMissionUniteLegale et economieSocialeSolidaireUniteLegale

df_demo = df_demo.drop(['societeMissionUniteLegale', 'economieSocialeSolidaireUniteLegale'])
df_demo.describe()

shape: (9, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ moisCreat ┆ departeme ┆ trancheEf ┆ caracter │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ ion       ┆ nt        ┆ fectifsSi ┆ eEmploye │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ege       ┆ urSiege  │
│           ┆           ┆ ---       ┆ str       ┆   ┆ f64       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1521227   ┆ 1521227   ┆ 16212     ┆ … ┆ 1.521227e ┆ 1521227   ┆ 1521227   ┆ 1521227  │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 1505015   ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2008-05-2 ┆ 2016-06-2 ┆ … ┆ 5.988163  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 2 04:04:1 ┆ 1 07:40:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 0.992126  ┆ 4.182087  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.674553  ┆ null      ┆ null      ┆ null     │
│ min       ┆ 005541552 ┆ 1970-01-0 ┆ 1983-02-2 ┆ … ┆ 1.0       ┆ 01        ┆ 00        ┆ N        │
│           ┆           ┆ 1         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2000-03-0 ┆ 2012-03-2 ┆ … ┆ 3.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2012-01-0 ┆ 2019-01-0 ┆ … ┆ 6.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 1         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2018-11-0 ┆ 2022-09-0 ┆ … ┆ 9.0       ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 3         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-06-1 ┆ 2025-10-2 ┆ … ┆ 12.0      ┆ 97        ┆ 53        ┆ O        │
│           ┆           ┆ 3         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
from datetime import datetime
import polars as pl

# Définition de l'année actuelle
current_year = datetime.now().year

# Calcul de l'ancienneté (en utilisant .with_columns et pl.col)
df_demo = df_demo.with_columns(
    (pl.lit(current_year) - pl.col('anneeCreation')).alias('anciennete')
)
print("--- Après ajout 'anciennete' ---")
df_demo.describe()

# Suppression de la colonne anneeCreation
df_demo = df_demo.drop(['anneeCreation', 'moisCreation'])

print("--- Après suppression 'anneeCreation' ---")
df_demo.describe()

--- Après ajout 'anciennete' ---
--- Après suppression 'anneeCreation' ---

shape: (9, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ dateCreat ┆ dateFerme ┆ … ┆ departeme ┆ trancheEf ┆ caractere ┆ ancienne │
│ ---       ┆ ---       ┆ ionUniteL ┆ ture      ┆   ┆ nt        ┆ fectifsSi ┆ Employeur ┆ te       │
│ str       ┆ str       ┆ egale     ┆ ---       ┆   ┆ ---       ┆ ege       ┆ Siege     ┆ ---      │
│           ┆           ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1521227   ┆ 1521227   ┆ 16212     ┆ … ┆ 1521227   ┆ 1521227   ┆ 1521227   ┆ 1.521227 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e6       │
│ null_coun ┆ 0         ┆ 0         ┆ 1505015   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2008-05-2 ┆ 2016-06-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ 17.05063 │
│           ┆           ┆ 2 04:04:1 ┆ 1 07:40:5 ┆   ┆           ┆           ┆           ┆ 2        │
│           ┆           ┆ 0.992126  ┆ 4.182087  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 12.59153 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ min       ┆ 005541552 ┆ 1970-01-0 ┆ 1983-02-2 ┆ … ┆ 01        ┆ 00        ┆ N         ┆ 0.0      │
│           ┆           ┆ 1         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 2000-03-0 ┆ 2012-03-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ 7.0      │
│           ┆           ┆ 1         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2012-01-0 ┆ 2019-01-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ 13.0     │
│           ┆           ┆ 1         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 2018-11-0 ┆ 2022-09-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ 25.0     │
│           ┆           ┆ 3         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999992357 ┆ 2025-06-1 ┆ 2025-10-2 ┆ … ┆ 97        ┆ 53        ┆ O         ┆ 55.0     │
│           ┆           ┆ 3         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

---

# DEBUT TRANSFORMATION BILAN

In [12]:
import polars as pl
import pyarrow.parquet as pq
import sys

filepath = "../Data/processed/sirene_bilan.parquet" 

print("--- Début de la lecture 'bypass' ---")

try:
    print(f"Lecture du fichier via PyArrow : {filepath}")
    table_arrow = pq.read_table(
        filepath,
    )
    
    print("Conversion de la table PyArrow en DataFrame Polars...")
    df_bilan = pl.from_arrow(table_arrow)
    
    print("--- SUCCÈS ! ---\n")
    print("Le DataFrame est maintenant dans Polars, prêt pour la transformation.")
    print(df_bilan.head())

except Exception as e:
    print(f"\n--- ERREUR ---", file=sys.stderr)
    print(f"Impossible de lire le fichier, même avec PyArrow : {e}", file=sys.stderr)

--- Début de la lecture 'bypass' ---
Lecture du fichier via PyArrow : ../Data/processed/sirene_bilan.parquet
Conversion de la table PyArrow en DataFrame Polars...
--- SUCCÈS ! ---

Le DataFrame est maintenant dans Polars, prêt pour la transformation.
shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ date_clot ┆ EG_Impots ┆ FA_Chiffr ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ ure_exerc ┆ Taxes     ┆ eAffaires ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ ice       ┆ ---       ┆ Ventes    ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆ ---       ┆ i32       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆ date      ┆           ┆ i32       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 005420120 ┆ 2018-12-3 ┆ 841098    ┆ 4623      ┆ … ┆ 0.0       ┆ 0.047087  ┆ 29.374216 ┆ 101.8593 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 99       │
│ 005420120 ┆ 2021-12-3 ┆ 2500000   ┆ 44073     ┆ … ┆ 0.0       ┆ 0.065831  ┆ 6.162617  ┆ 14.06566 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005420120 ┆ 2017-12-3 ┆ 441247    ┆ 26192     ┆ … ┆ 0.0       ┆ 0.03138   ┆ 3.745877  ┆ 17.20460 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005420120 ┆ 2016-12-3 ┆ 586967    ┆ 11836     ┆ … ┆ 0.0       ┆ 0.022292  ┆ 8.805762  ┆ 66.05635 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 005420120 ┆ 2019-12-3 ┆ 0         ┆ 48370     ┆ … ┆ 0.0       ┆ 0.05589   ┆ 4.502626  ┆ 10.75797 │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
df_bilan.describe()

shape: (9, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ date_clot ┆ EG_Impots ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ ---       ┆ ure_exerc ┆ Taxes     ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ str       ┆ ice       ┆ ---       ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆           ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆           ┆ str       ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3706645   ┆ 3706645   ┆ 3.706645e ┆ … ┆ 3.706645e ┆ 3.706645e ┆ 3.706645e ┆ 3.706645 │
│           ┆           ┆           ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2019-10-0 ┆ 1.1025e6  ┆ … ┆ 8.7383e8  ┆ 2.1672e11 ┆ 1.1745e12 ┆ 3.0131e1 │
│           ┆           ┆ 6 17:39:4 ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│           ┆           ┆ 9.194433  ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ 1.6389e7  ┆ … ┆ 1.1443e12 ┆ 1.7773e13 ┆ 1.6774e13 ┆ 5.1192e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ min       ┆ 005420120 ┆ 1919-09-3 ┆ -2.1475e9 ┆ … ┆ -7.2972e1 ┆ -2.1475e1 ┆ -2.1460e1 ┆ -2.1475e │
│           ┆           ┆ 0         ┆           ┆   ┆ 2         ┆ 5         ┆ 5         ┆ 15       │
│ 25%       ┆ null      ┆ 2017-12-3 ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.024045  ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ 2019-12-3 ┆ 82447.0   ┆ … ┆ 0.0       ┆ 0.084052  ┆ 1.003174  ┆ 60.75291 │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ 75%       ┆ null      ┆ 2021-09-3 ┆ 431133.0  ┆ … ┆ 0.0       ┆ 0.332404  ┆ 1.3592e11 ┆ 3.7060e1 │
│           ┆           ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ max       ┆ 999990542 ┆ 2029-12-3 ┆ 2.1475e9  ┆ … ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e1 │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
# supprime la colonne date_cloture_exercice

df_bilan = df_bilan.drop(['date_cloture_exercice'])

In [15]:
df_bilan.group_by("AnneeClotureExercice").agg(pl.len()).sort("AnneeClotureExercice")

shape: (22, 2)
┌──────────────────────┬────────┐
│ AnneeClotureExercice ┆ len    │
│ ---                  ┆ ---    │
│ i32                  ┆ u32    │
╞══════════════════════╪════════╡
│ 1919                 ┆ 1      │
│ 2003                 ┆ 1      │
│ 2004                 ┆ 1      │
│ 2007                 ┆ 2      │
│ 2008                 ┆ 1      │
│ …                    ┆ …      │
│ 2021                 ┆ 500065 │
│ 2022                 ┆ 435016 │
│ 2023                 ┆ 99219  │
│ 2024                 ┆ 12     │
│ 2029                 ┆ 1      │
└──────────────────────┴────────┘

In [16]:
# Je veux que tu me gardes que les lignes où AnneeClotureExercice est entre 2010 et 2022 inclus

df_bilan = df_bilan.filter((df_bilan['AnneeClotureExercice'] >= 2010) & (df_bilan['AnneeClotureExercice'] <= 2022))
df_bilan.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ ---       ┆ Taxes     ┆ eAffaires ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ str       ┆ ---       ┆ Ventes    ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆           ┆ f64       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3607402   ┆ 3.607402e ┆ 3.607402e ┆ … ┆ 3.607402e ┆ 3.607402e ┆ 3.607402e ┆ 3.607402 │
│           ┆           ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 1.1087e6  ┆ 1.4819e6  ┆ … ┆ 8.9785e8  ┆ 2.1960e11 ┆ 1.1858e12 ┆ 3.0327e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ std       ┆ null      ┆ 1.6493e7  ┆ 2.7876e7  ┆ … ┆ 1.1599e12 ┆ 1.7879e13 ┆ 1.6883e13 ┆ 5.1335e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ min       ┆ 005420120 ┆ -2.1475e9 ┆ -5.4749e8 ┆ … ┆ -7.2972e1 ┆ -2.1475e1 ┆ -2.1460e1 ┆ -2.1475e │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 5         ┆ 15       │
│ 25%       ┆ null      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.02418   ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ null      ┆ 81331.0   ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.084342  ┆ 1.004492  ┆ 80.92526 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ 75%       ┆ null      ┆ 430613.0  ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.332925  ┆ 1.4000e11 ┆ 3.7486e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ max       ┆ 999990542 ┆ 2.1475e9  ┆ 2.1475e9  ┆ … ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
# oragnise la dataframe par anneeClotureExercice croissant et par siren

df_bilan = df_bilan.sort(['siren', 'AnneeClotureExercice'])
df_bilan.head(10)

shape: (10, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ DL_Dettes ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ Taxes     ┆ eAffaires ┆ CourtTerm ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ ---       ┆ Ventes    ┆ e         ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆ i32       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆           ┆ i32       ┆ i32       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 005420120 ┆ 586967    ┆ 11836     ┆ 92013428  ┆ … ┆ 0.0       ┆ 0.022292  ┆ 8.805762  ┆ 66.05635 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 005420120 ┆ 441247    ┆ 26192     ┆ 90919571  ┆ … ┆ 0.0       ┆ 0.03138   ┆ 3.745877  ┆ 17.20460 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005420120 ┆ 841098    ┆ 4623      ┆ 90269342  ┆ … ┆ 0.0       ┆ 0.047087  ┆ 29.374216 ┆ 101.8593 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 99       │
│ 005420120 ┆ 0         ┆ 48370     ┆ 89288445  ┆ … ┆ 0.0       ┆ 0.05589   ┆ 4.502626  ┆ 10.75797 │
│ 005420120 ┆ 885730    ┆ 72481     ┆ 88446360  ┆ … ┆ 0.0       ┆ 0.059288  ┆ 4.723734  ┆ 10.01532 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 005420120 ┆ 2500000   ┆ 44073     ┆ 86469939  ┆ … ┆ 0.0       ┆ 0.065831  ┆ 6.162617  ┆ 14.06566 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005420120 ┆ 854623    ┆ 13906     ┆ 85387013  ┆ … ┆ 0.0       ┆ 0.070428  ┆ 17.674673 ┆ 37.82633 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005450119 ┆ 1800      ┆ 0         ┆ -281363   ┆ … ┆ 0.0       ┆ 0.071338  ┆ 0.0       ┆ 0.0      │
│ 005450119 ┆ 1475      ┆ 0         ┆ -282592   ┆ … ┆ 0.0       ┆ 0.071357  ┆ 0.0       ┆ 0.0      │
│ 005450119 ┆ 0         ┆ 0         ┆ -283927   ┆ … ┆ 0.0       ┆ 0.071824  ┆ 0.0       ┆ 0.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [19]:
df_bilan.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ ---       ┆ Taxes     ┆ eAffaires ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ str       ┆ ---       ┆ Ventes    ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆           ┆ f64       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3607402   ┆ 3.607402e ┆ 3.607402e ┆ … ┆ 3.607402e ┆ 3.607402e ┆ 3.607402e ┆ 3.607402 │
│           ┆           ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 1.1087e6  ┆ 1.4819e6  ┆ … ┆ 8.9785e8  ┆ 2.1960e11 ┆ 1.1858e12 ┆ 3.0327e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ std       ┆ null      ┆ 1.6493e7  ┆ 2.7876e7  ┆ … ┆ 1.1599e12 ┆ 1.7879e13 ┆ 1.6883e13 ┆ 5.1335e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ min       ┆ 005420120 ┆ -2.1475e9 ┆ -5.4749e8 ┆ … ┆ -7.2972e1 ┆ -2.1475e1 ┆ -2.1460e1 ┆ -2.1475e │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 5         ┆ 15       │
│ 25%       ┆ null      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.02418   ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ null      ┆ 81331.0   ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.084342  ┆ 1.004492  ┆ 80.92526 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ 75%       ┆ null      ┆ 430613.0  ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.332925  ┆ 1.4000e11 ┆ 3.7486e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ max       ┆ 999990542 ┆ 2.1475e9  ┆ 2.1475e9  ┆ … ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
# drop moi toutes les ligens ou HN_RésultatNet est 0

df_bilan = df_bilan.filter(df_bilan['HN_RésultatNet'] != 0)

In [21]:
df_bilan.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ ---       ┆ Taxes     ┆ eAffaires ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ str       ┆ ---       ┆ Ventes    ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆           ┆ f64       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2741412   ┆ 2.741412e ┆ 2.741412e ┆ … ┆ 2.741412e ┆ 2.741412e ┆ 2.741412e ┆ 2.741412 │
│           ┆           ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 1.3147e6  ┆ 1.9255e6  ┆ … ┆ 2.3712e8  ┆ 4.2650e10 ┆ 1.5384e12 ┆ 3.6329e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ std       ┆ null      ┆ 1.8729e7  ┆ 3.1722e7  ┆ … ┆ 2.9055e11 ┆ 6.5704e12 ┆ 1.9243e13 ┆ 5.4280e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ min       ┆ 005420120 ┆ -2.1475e9 ┆ -5.4749e8 ┆ … ┆ -7.2972e1 ┆ -2.1475e1 ┆ -2.1460e1 ┆ -2.1475e │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆ 5         ┆ 5         ┆ 15       │
│ 25%       ┆ null      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.027167  ┆ 0.0       ┆ 1.303525 │
│ 50%       ┆ null      ┆ 50045.0   ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.096656  ┆ 39.4362   ┆ 6.7920e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ 75%       ┆ null      ┆ 393311.0  ┆ 2377.0    ┆ … ┆ 0.0       ┆ 0.41415   ┆ 3.4505e11 ┆ 7.4839e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ max       ┆ 999990542 ┆ 2.1475e9  ┆ 2.1475e9  ┆ … ┆ 4.6815e14 ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
# garde moi que les siren qui on une ligne pour chaque année de 2016 à 2022

siren_counts = df_bilan.filter((df_bilan['AnneeClotureExercice'] >= 2016) & (df_bilan['AnneeClotureExercice'] <= 2022)) \
    .group_by('siren') \
    .agg(pl.count()) \
    .filter(pl.col('count') == 7) \
    .select('siren')
df_bilan = df_bilan.join(siren_counts, on='siren', how='inner')
df_bilan.describe()

/var/folders/sp/97__4mlj3nbc2fssvlgn3_nh0000gn/T/ipykernel_57979/419857990.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count()) \

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ ---       ┆ Taxes     ┆ eAffaires ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ str       ┆ ---       ┆ Ventes    ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆           ┆ f64       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 652153    ┆ 652153.0  ┆ 652153.0  ┆ … ┆ 652153.0  ┆ 652153.0  ┆ 652153.0  ┆ 652153.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2.6455e6  ┆ 4.4185e6  ┆ … ┆ 2.5009e8  ┆ 4.0682e10 ┆ 3.4344e12 ┆ 7.8018e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ std       ┆ null      ┆ 2.8937e7  ┆ 5.3012e7  ┆ … ┆ 1.3602e11 ┆ 5.0496e12 ┆ 3.2501e13 ┆ 7.9554e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ min       ┆ 005420120 ┆ -2.1475e9 ┆ -5.1449e8 ┆ … ┆ -30.85959 ┆ -1.6408e1 ┆ -3.4733e1 ┆ -2.1475e │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆ 2         ┆ 3         ┆ 15       │
│ 25%       ┆ null      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.02668   ┆ 1.0       ┆ 1.676128 │
│ 50%       ┆ null      ┆ 84815.0   ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.095455  ┆ 249.09502 ┆ 1.2136e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9         ┆ 1        │
│ 75%       ┆ null      ┆ 792462.0  ┆ 17030.0   ┆ … ┆ 0.0       ┆ 0.406444  ┆ 7.7623e11 ┆ 1.7215e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ max       ┆ 999990005 ┆ 2.1475e9  ┆ 2.1475e9  ┆ … ┆ 1.0290e14 ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1475e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
df_bilan.head(10)

shape: (10, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ DL_Dettes ┆ … ┆ ratio_cap ┆ ratio_tre ┆ ratio_res ┆ ratio_re │
│ ---       ┆ Taxes     ┆ eAffaires ┆ CourtTerm ┆   ┆ itaux_pro ┆ sorerie   ┆ ultat_fin ┆ sultat_e │
│ str       ┆ ---       ┆ Ventes    ┆ e         ┆   ┆ pres      ┆ ---       ┆ ancier    ┆ xception │
│           ┆ i32       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ nel      │
│           ┆           ┆ i32       ┆ i32       ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 005420120 ┆ 586967    ┆ 11836     ┆ 92013428  ┆ … ┆ 0.0       ┆ 0.022292  ┆ 8.805762  ┆ 66.05635 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 005420120 ┆ 441247    ┆ 26192     ┆ 90919571  ┆ … ┆ 0.0       ┆ 0.03138   ┆ 3.745877  ┆ 17.20460 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005420120 ┆ 841098    ┆ 4623      ┆ 90269342  ┆ … ┆ 0.0       ┆ 0.047087  ┆ 29.374216 ┆ 101.8593 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 99       │
│ 005420120 ┆ 0         ┆ 48370     ┆ 89288445  ┆ … ┆ 0.0       ┆ 0.05589   ┆ 4.502626  ┆ 10.75797 │
│ 005420120 ┆ 885730    ┆ 72481     ┆ 88446360  ┆ … ┆ 0.0       ┆ 0.059288  ┆ 4.723734  ┆ 10.01532 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 005420120 ┆ 2500000   ┆ 44073     ┆ 86469939  ┆ … ┆ 0.0       ┆ 0.065831  ┆ 6.162617  ┆ 14.06566 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005420120 ┆ 854623    ┆ 13906     ┆ 85387013  ┆ … ┆ 0.0       ┆ 0.070428  ┆ 17.674673 ┆ 37.82633 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 005580501 ┆ 0         ┆ 0         ┆ 774186    ┆ … ┆ 0.0       ┆ 1.551181  ┆ 0.0       ┆ 5.2258e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ 005580501 ┆ 0         ┆ 0         ┆ 495538    ┆ … ┆ 0.0       ┆ 6.294653  ┆ 5.2760e9  ┆ 5.5062e1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ 005580501 ┆ 0         ┆ 0         ┆ 576084    ┆ … ┆ 0.0       ┆ 5.290306  ┆ -1.8e7    ┆ -1.8e7   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
import polars as pl

# ----------------------------------------------------------------------
# Étape 0 : Tri (CORRIGÉ)
# Nous trions par 'siren' puis par 'AnneeClotureExercice' pour garantir
# que le shift(1) prenne bien la valeur de l'année précédente (N-1).
# ----------------------------------------------------------------------
df_bilan = df_bilan.sort(["siren", "AnneeClotureExercice"])

# ----------------------------------------------------------------------
# Étape 1 : Définition des Variables & Création des 4 colonnes de variation (CORRIGÉ)
# ----------------------------------------------------------------------

# Variables de Colonnes à utiliser (pour la lisibilité)
COL_RN = 'HN_RésultatNet'

df_bilan = df_bilan.with_columns([
    
    # 1. Variation Résultat Net N vs N-1
    (pl.col(COL_RN) - pl.col(COL_RN).shift(1).over('siren')).alias('variation_resultat_net_N-1'),
    
    # 2. Variation Résultat Net N vs N-2
    (pl.col(COL_RN) - pl.col(COL_RN).shift(2).over('siren')).alias('variation_resultat_net_N-2'),
    
])

df_bilan.head(10)

shape: (10, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ DL_Dettes ┆ … ┆ ratio_res ┆ ratio_res ┆ variation ┆ variatio │
│ ---       ┆ Taxes     ┆ eAffaires ┆ CourtTerm ┆   ┆ ultat_fin ┆ ultat_exc ┆ _resultat ┆ n_result │
│ str       ┆ ---       ┆ Ventes    ┆ e         ┆   ┆ ancier    ┆ eptionnel ┆ _net_N-1  ┆ at_net_N │
│           ┆ i32       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ -2       │
│           ┆           ┆ i32       ┆ i32       ┆   ┆ f64       ┆ f64       ┆ i32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 005420120 ┆ 586967    ┆ 11836     ┆ 92013428  ┆ … ┆ 8.805762  ┆ 66.056353 ┆ null      ┆ null     │
│ 005420120 ┆ 441247    ┆ 26192     ┆ 90919571  ┆ … ┆ 3.745877  ┆ 17.204604 ┆ -115638   ┆ null     │
│ 005420120 ┆ 841098    ┆ 4623      ┆ 90269342  ┆ … ┆ 29.374216 ┆ 101.85939 ┆ 87560     ┆ -28078   │
│           ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ 005420120 ┆ 0         ┆ 48370     ┆ 89288445  ┆ … ┆ 4.502626  ┆ 10.75797  ┆ -681016   ┆ -593456  │
│ 005420120 ┆ 885730    ┆ 72481     ┆ 88446360  ┆ … ┆ 4.723734  ┆ 10.015328 ┆ 162464    ┆ -518552  │
│ 005420120 ┆ 2500000   ┆ 44073     ┆ 86469939  ┆ … ┆ 6.162617  ┆ 14.065664 ┆ -1167183  ┆ -1004719 │
│ 005420120 ┆ 854623    ┆ 13906     ┆ 85387013  ┆ … ┆ 17.674673 ┆ 37.826334 ┆ 893666    ┆ -273517  │
│ 005580501 ┆ 0         ┆ 0         ┆ 774186    ┆ … ┆ 0.0       ┆ 5.2258e11 ┆ null      ┆ null     │
│ 005580501 ┆ 0         ┆ 0         ┆ 495538    ┆ … ┆ 5.2760e9  ┆ 5.5062e11 ┆ 762319    ┆ null     │
│ 005580501 ┆ 0         ┆ 0         ┆ 576084    ┆ … ┆ -1.8e7    ┆ -1.8e7    ┆ 359194    ┆ 1121513  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
# Je veux que tu drop toutes les colonnes ou variation_resultat_net_N-2 est égale à null

df_bilan = df_bilan.filter(pl.col('variation_resultat_net_N-2').is_not_null())
df_bilan.head(10)

shape: (10, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ DL_Dettes ┆ … ┆ ratio_res ┆ ratio_res ┆ variation ┆ variatio │
│ ---       ┆ Taxes     ┆ eAffaires ┆ CourtTerm ┆   ┆ ultat_fin ┆ ultat_exc ┆ _resultat ┆ n_result │
│ str       ┆ ---       ┆ Ventes    ┆ e         ┆   ┆ ancier    ┆ eptionnel ┆ _net_N-1  ┆ at_net_N │
│           ┆ i32       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ -2       │
│           ┆           ┆ i32       ┆ i32       ┆   ┆ f64       ┆ f64       ┆ i32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 005420120 ┆ 841098    ┆ 4623      ┆ 90269342  ┆ … ┆ 29.374216 ┆ 101.85939 ┆ 87560     ┆ -28078   │
│           ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ 005420120 ┆ 0         ┆ 48370     ┆ 89288445  ┆ … ┆ 4.502626  ┆ 10.75797  ┆ -681016   ┆ -593456  │
│ 005420120 ┆ 885730    ┆ 72481     ┆ 88446360  ┆ … ┆ 4.723734  ┆ 10.015328 ┆ 162464    ┆ -518552  │
│ 005420120 ┆ 2500000   ┆ 44073     ┆ 86469939  ┆ … ┆ 6.162617  ┆ 14.065664 ┆ -1167183  ┆ -1004719 │
│ 005420120 ┆ 854623    ┆ 13906     ┆ 85387013  ┆ … ┆ 17.674673 ┆ 37.826334 ┆ 893666    ┆ -273517  │
│ 005580501 ┆ 0         ┆ 0         ┆ 576084    ┆ … ┆ -1.8e7    ┆ -1.8e7    ┆ 359194    ┆ 1121513  │
│ 005580501 ┆ 0         ┆ 0         ┆ 593983    ┆ … ┆ 0.0       ┆ 0.0       ┆ -62647    ┆ 296547   │
│ 005580501 ┆ 4586      ┆ 0         ┆ 608645    ┆ … ┆ 0.0       ┆ 0.0       ┆ -3237     ┆ -65884   │
│ 005580501 ┆ 0         ┆ 0         ┆ 5139261   ┆ … ┆ 0.0       ┆ 0.0       ┆ 215954    ┆ 212717   │
│ 005580501 ┆ 5277      ┆ 0         ┆ 5132555   ┆ … ┆ 0.0       ┆ 0.0       ┆ -237322   ┆ -21368   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [26]:
df_bilan.describe()

shape: (9, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ … ┆ ratio_res ┆ ratio_res ┆ variation ┆ variatio │
│ ---       ┆ ---       ┆ Taxes     ┆ eAffaires ┆   ┆ ultat_fin ┆ ultat_exc ┆ _resultat ┆ n_result │
│ str       ┆ str       ┆ ---       ┆ Ventes    ┆   ┆ ancier    ┆ eptionnel ┆ _net_N-1  ┆ at_net_N │
│           ┆           ┆ f64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ -2       │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 468235    ┆ 468235.0  ┆ 468235.0  ┆ … ┆ 468235.0  ┆ 468235.0  ┆ 468235.0  ┆ 468235.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2.7265e6  ┆ 4.5188e6  ┆ … ┆ 3.4352e12 ┆ 8.0605e12 ┆ 105882.77 ┆ 177997.3 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0664      ┆ 50525    │
│ std       ┆ null      ┆ 2.9652e7  ┆ 5.3889e7  ┆ … ┆ 3.1434e13 ┆ 8.1620e13 ┆ 2.7929e7  ┆ 2.8613e7 │
│ min       ┆ 005420120 ┆ -2.1475e9 ┆ -5.1449e8 ┆ … ┆ -3.4733e1 ┆ -2.1475e1 ┆ -2.1420e9 ┆ -2.1329e │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 5         ┆           ┆ 9        │
│ 25%       ┆ null      ┆ 0.0       ┆ 0.0       ┆ … ┆ 1.0       ┆ 1.812911  ┆ -52791.0  ┆ -55005.0 │
│ 50%       ┆ null      ┆ 80668.0   ┆ 0.0       ┆ … ┆ 172.37455 ┆ 1.2736e11 ┆ 1221.0    ┆ 3698.0   │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ 804765.0  ┆ 14084.0   ┆ … ┆ 7.6688e11 ┆ 1.8103e12 ┆ 79492.0   ┆ 107779.0 │
│ max       ┆ 999990005 ┆ 2.1475e9  ┆ 2.1475e9  ┆ … ┆ 2.1475e15 ┆ 2.1475e15 ┆ 2.1452e9  ┆ 2.1462e9 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [27]:
# Je veux que tu crées une colonnes par siren qui va chercher par siren de l'années N+1 qui va s'appeler Y_RN

df_bilan = df_bilan.with_columns([
    pl.col('HN_RésultatNet').shift(-1).over('siren').alias('Y_RN')
])
df_bilan.head(10)

shape: (10, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ DL_Dettes ┆ … ┆ ratio_res ┆ variation ┆ variation ┆ Y_RN     │
│ ---       ┆ Taxes     ┆ eAffaires ┆ CourtTerm ┆   ┆ ultat_exc ┆ _resultat ┆ _resultat ┆ ---      │
│ str       ┆ ---       ┆ Ventes    ┆ e         ┆   ┆ eptionnel ┆ _net_N-1  ┆ _net_N-2  ┆ i32      │
│           ┆ i32       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆          │
│           ┆           ┆ i32       ┆ i32       ┆   ┆ f64       ┆ i32       ┆ i32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 005420120 ┆ 841098    ┆ 4623      ┆ 90269342  ┆ … ┆ 101.85939 ┆ 87560     ┆ -28078    ┆ -970147  │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ 005420120 ┆ 0         ┆ 48370     ┆ 89288445  ┆ … ┆ 10.75797  ┆ -681016   ┆ -593456   ┆ -807683  │
│ 005420120 ┆ 885730    ┆ 72481     ┆ 88446360  ┆ … ┆ 10.015328 ┆ 162464    ┆ -518552   ┆ -1974866 │
│ 005420120 ┆ 2500000   ┆ 44073     ┆ 86469939  ┆ … ┆ 14.065664 ┆ -1167183  ┆ -1004719  ┆ -1081200 │
│ 005420120 ┆ 854623    ┆ 13906     ┆ 85387013  ┆ … ┆ 37.826334 ┆ 893666    ┆ -273517   ┆ null     │
│ 005580501 ┆ 0         ┆ 0         ┆ 576084    ┆ … ┆ -1.8e7    ┆ 359194    ┆ 1121513   ┆ 17899    │
│ 005580501 ┆ 0         ┆ 0         ┆ 593983    ┆ … ┆ 0.0       ┆ -62647    ┆ 296547    ┆ 14662    │
│ 005580501 ┆ 4586      ┆ 0         ┆ 608645    ┆ … ┆ 0.0       ┆ -3237     ┆ -65884    ┆ 230616   │
│ 005580501 ┆ 0         ┆ 0         ┆ 5139261   ┆ … ┆ 0.0       ┆ 215954    ┆ 212717    ┆ -6706    │
│ 005580501 ┆ 5277      ┆ 0         ┆ 5132555   ┆ … ┆ 0.0       ┆ -237322   ┆ -21368    ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [28]:
# drop toutes les colonnes ou Y_RN est égale à null

df_bilan = df_bilan.filter(pl.col('Y_RN').is_not_null())
df_bilan.head(15)

shape: (15, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ DL_Dettes ┆ … ┆ ratio_res ┆ variation ┆ variation ┆ Y_RN     │
│ ---       ┆ Taxes     ┆ eAffaires ┆ CourtTerm ┆   ┆ ultat_exc ┆ _resultat ┆ _resultat ┆ ---      │
│ str       ┆ ---       ┆ Ventes    ┆ e         ┆   ┆ eptionnel ┆ _net_N-1  ┆ _net_N-2  ┆ i32      │
│           ┆ i32       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆          │
│           ┆           ┆ i32       ┆ i32       ┆   ┆ f64       ┆ i32       ┆ i32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 005420120 ┆ 841098    ┆ 4623      ┆ 90269342  ┆ … ┆ 101.85939 ┆ 87560     ┆ -28078    ┆ -970147  │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ 005420120 ┆ 0         ┆ 48370     ┆ 89288445  ┆ … ┆ 10.75797  ┆ -681016   ┆ -593456   ┆ -807683  │
│ 005420120 ┆ 885730    ┆ 72481     ┆ 88446360  ┆ … ┆ 10.015328 ┆ 162464    ┆ -518552   ┆ -1974866 │
│ 005420120 ┆ 2500000   ┆ 44073     ┆ 86469939  ┆ … ┆ 14.065664 ┆ -1167183  ┆ -1004719  ┆ -1081200 │
│ 005580501 ┆ 0         ┆ 0         ┆ 576084    ┆ … ┆ -1.8e7    ┆ 359194    ┆ 1121513   ┆ 17899    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 005720651 ┆ 102434    ┆ 0         ┆ -54086    ┆ … ┆ 6.4025e10 ┆ 148540    ┆ 64932     ┆ 61661    │
│ 005720651 ┆ 26859     ┆ 0         ┆ 7574      ┆ … ┆ 7.1967e10 ┆ 34405     ┆ 182945    ┆ 54770    │
│ 005720651 ┆ 8848      ┆ 0         ┆ 62344     ┆ … ┆ 7.3448e10 ┆ -6891     ┆ 27514     ┆ 46401    │
│ 005720651 ┆ 9333      ┆ 0         ┆ 108744    ┆ … ┆ 7.4771e10 ┆ -8369     ┆ -15260    ┆ 48298    │
│ 005720651 ┆ 0         ┆ 0         ┆ 157043    ┆ … ┆ 7.6064e10 ┆ 1897      ┆ -6472     ┆ 50295    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [29]:
df_bilan.describe()

shape: (9, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ EG_Impots ┆ FA_Chiffr ┆ … ┆ ratio_res ┆ variation ┆ variation ┆ Y_RN     │
│ ---       ┆ ---       ┆ Taxes     ┆ eAffaires ┆   ┆ ultat_exc ┆ _resultat ┆ _resultat ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ Ventes    ┆   ┆ eptionnel ┆ _net_N-1  ┆ _net_N-2  ┆ f64      │
│           ┆           ┆ f64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆          │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 376276    ┆ 376276.0  ┆ 376276.0  ┆ … ┆ 376276.0  ┆ 376276.0  ┆ 376276.0  ┆ 376276.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2.6393e6  ┆ 4.3870e6  ┆ … ┆ 7.8009e12 ┆ 73430.659 ┆ -6160.654 ┆ 1.0400e6 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 542       ┆ 147       ┆          │
│ std       ┆ null      ┆ 2.8392e7  ┆ 5.2708e7  ┆ … ┆ 8.0277e13 ┆ 2.7461e7  ┆ 2.7466e7  ┆ 2.8633e7 │
│ min       ┆ 005420120 ┆ -2.1475e9 ┆ -5.1449e8 ┆ … ┆ -2.1475e1 ┆ -2.1420e9 ┆ -2.1329e9 ┆ -2.1475e │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆ 9        │
│ 25%       ┆ null      ┆ 0.0       ┆ 0.0       ┆ … ┆ 1.819213  ┆ -50672.0  ┆ -61093.0  ┆ -990.0   │
│ 50%       ┆ null      ┆ 87891.0   ┆ 0.0       ┆ … ┆ 1.2864e11 ┆ 1219.0    ┆ 1866.0    ┆ 55055.0  │
│ 75%       ┆ null      ┆ 809359.0  ┆ 14487.0   ┆ … ┆ 1.7707e12 ┆ 75576.0   ┆ 90405.0   ┆ 303511.0 │
│ max       ┆ 999990005 ┆ 2.1475e9  ┆ 2.1475e9  ┆ … ┆ 2.1475e15 ┆ 2.1287e9  ┆ 2.1245e9  ┆ 2.1475e9 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
# je veux que du me supprimer les colonnes DM_DettesLongTerme, DF_CapitauxPropres, FB_AchatsMarchandises, FA_ChiffreAffairesVentes, EG_ImpotsTaxes

df_bilan = df_bilan.drop(['DM_DettesLongTerme', 'DF_CapitauxPropres', 'FB_AchatsMarchandises', 'FA_ChiffreAffairesVentes', 'EG_ImpotsTaxes', 'ratio_marge_brute', 'ratio_capitaux_propres'])
df_bilan.describe()

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ DL_Dettes ┆ HN_Résult ┆ … ┆ ratio_res ┆ variation ┆ variation ┆ Y_RN     │
│ ---       ┆ ---       ┆ CourtTerm ┆ atNet     ┆   ┆ ultat_exc ┆ _resultat ┆ _resultat ┆ ---      │
│ str       ┆ str       ┆ e         ┆ ---       ┆   ┆ eptionnel ┆ _net_N-1  ┆ _net_N-2  ┆ f64      │
│           ┆           ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆          │
│           ┆           ┆ f64       ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 376276    ┆ 376276.0  ┆ 376276.0  ┆ … ┆ 376276.0  ┆ 376276.0  ┆ 376276.0  ┆ 376276.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 1.0407e7  ┆ 944421.22 ┆ … ┆ 7.8009e12 ┆ 73430.659 ┆ -6160.654 ┆ 1.0400e6 │
│           ┆           ┆           ┆ 8896      ┆   ┆           ┆ 542       ┆ 147       ┆          │
│ std       ┆ null      ┆ 9.3864e7  ┆ 2.6947e7  ┆ … ┆ 8.0277e13 ┆ 2.7461e7  ┆ 2.7466e7  ┆ 2.8633e7 │
│ min       ┆ 005420120 ┆ -2.1475e9 ┆ -2.1475e9 ┆ … ┆ -2.1475e1 ┆ -2.1420e9 ┆ -2.1329e9 ┆ -2.1475e │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆ 9        │
│ 25%       ┆ null      ┆ 139291.0  ┆ -714.0    ┆ … ┆ 1.819213  ┆ -50672.0  ┆ -61093.0  ┆ -990.0   │
│ 50%       ┆ null      ┆ 645583.0  ┆ 52297.0   ┆ … ┆ 1.2864e11 ┆ 1219.0    ┆ 1866.0    ┆ 55055.0  │
│ 75%       ┆ null      ┆ 2.538094e ┆ 278724.0  ┆ … ┆ 1.7707e12 ┆ 75576.0   ┆ 90405.0   ┆ 303511.0 │
│           ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 999990005 ┆ 2.1475e9  ┆ 2.1475e9  ┆ … ┆ 2.1475e15 ┆ 2.1287e9  ┆ 2.1245e9  ┆ 2.1475e9 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
# fait un join entre df_demo et df_bilan sur siren sans les colonnes

df_final = df_bilan.join(df_demo, on='siren', how='inner')
df_final.describe()

shape: (9, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ DL_Dettes ┆ HN_Résult ┆ … ┆ departeme ┆ trancheEf ┆ caractere ┆ ancienne │
│ ---       ┆ ---       ┆ CourtTerm ┆ atNet     ┆   ┆ nt        ┆ fectifsSi ┆ Employeur ┆ te       │
│ str       ┆ str       ┆ e         ┆ ---       ┆   ┆ ---       ┆ ege       ┆ Siege     ┆ ---      │
│           ┆           ┆ ---       ┆ f64       ┆   ┆ str       ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆ f64       ┆           ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 202459    ┆ 202459.0  ┆ 202459.0  ┆ … ┆ 202459    ┆ 202459    ┆ 202459    ┆ 202459.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 8.5266e6  ┆ 748079.15 ┆ … ┆ null      ┆ null      ┆ null      ┆ 26.81744 │
│           ┆           ┆           ┆ 2653      ┆   ┆           ┆           ┆           ┆ 5        │
│ std       ┆ null      ┆ 7.5910e7  ┆ 2.1788e7  ┆ … ┆ null      ┆ null      ┆ null      ┆ 11.37956 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ min       ┆ 007050040 ┆ -2.1475e9 ┆ -2.1475e9 ┆ … ┆ 01        ┆ 00        ┆ N         ┆ 2.0      │
│ 25%       ┆ null      ┆ 221131.0  ┆ 7637.0    ┆ … ┆ null      ┆ null      ┆ null      ┆ 18.0     │
│ 50%       ┆ null      ┆ 761061.0  ┆ 79538.0   ┆ … ┆ null      ┆ null      ┆ null      ┆ 25.0     │
│ 75%       ┆ null      ┆ 2.713805e ┆ 333856.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ 35.0     │
│           ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 998591507 ┆ 2.1475e9  ┆ 2.1475e9  ┆ … ┆ 97        ┆ 53        ┆ O         ┆ 55.0     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [32]:
# drop les colonnes dateFermeture et is_failed_in_3y

df_final = df_final.drop(['dateFermeture', 'is_failed_in_3y'])
df_final.describe()

shape: (9, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ DL_Dettes ┆ HN_Résult ┆ … ┆ departeme ┆ trancheEf ┆ caractere ┆ ancienne │
│ ---       ┆ ---       ┆ CourtTerm ┆ atNet     ┆   ┆ nt        ┆ fectifsSi ┆ Employeur ┆ te       │
│ str       ┆ str       ┆ e         ┆ ---       ┆   ┆ ---       ┆ ege       ┆ Siege     ┆ ---      │
│           ┆           ┆ ---       ┆ f64       ┆   ┆ str       ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆ f64       ┆           ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 202459    ┆ 202459.0  ┆ 202459.0  ┆ … ┆ 202459    ┆ 202459    ┆ 202459    ┆ 202459.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 8.5266e6  ┆ 748079.15 ┆ … ┆ null      ┆ null      ┆ null      ┆ 26.81744 │
│           ┆           ┆           ┆ 2653      ┆   ┆           ┆           ┆           ┆ 5        │
│ std       ┆ null      ┆ 7.5910e7  ┆ 2.1788e7  ┆ … ┆ null      ┆ null      ┆ null      ┆ 11.37956 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ min       ┆ 007050040 ┆ -2.1475e9 ┆ -2.1475e9 ┆ … ┆ 01        ┆ 00        ┆ N         ┆ 2.0      │
│ 25%       ┆ null      ┆ 221131.0  ┆ 7637.0    ┆ … ┆ null      ┆ null      ┆ null      ┆ 18.0     │
│ 50%       ┆ null      ┆ 761061.0  ┆ 79538.0   ┆ … ┆ null      ┆ null      ┆ null      ┆ 25.0     │
│ 75%       ┆ null      ┆ 2.713805e ┆ 333856.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ 35.0     │
│           ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 998591507 ┆ 2.1475e9  ┆ 2.1475e9  ┆ … ┆ 97        ┆ 53        ┆ O         ┆ 55.0     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [33]:
#réorganise les colonnes pour que siren soit la première colonne et AnneeClotureExercice la deuxième

cols = df_final.columns
cols.remove('siren')
cols.remove('AnneeClotureExercice')
new_order = ['siren', 'AnneeClotureExercice'] + cols
df_final = df_final.select(new_order)
df_final.describe()

shape: (9, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ AnneeClot ┆ DL_Dettes ┆ … ┆ departeme ┆ trancheEf ┆ caractere ┆ ancienne │
│ ---       ┆ ---       ┆ ureExerci ┆ CourtTerm ┆   ┆ nt        ┆ fectifsSi ┆ Employeur ┆ te       │
│ str       ┆ str       ┆ ce        ┆ e         ┆   ┆ ---       ┆ ege       ┆ Siege     ┆ ---      │
│           ┆           ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 202459    ┆ 202459.0  ┆ 202459.0  ┆ … ┆ 202459    ┆ 202459    ┆ 202459    ┆ 202459.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2019.4413 ┆ 8.5266e6  ┆ … ┆ null      ┆ null      ┆ null      ┆ 26.81744 │
│           ┆           ┆ 58        ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ std       ┆ null      ┆ 1.180506  ┆ 7.5910e7  ┆ … ┆ null      ┆ null      ┆ null      ┆ 11.37956 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ min       ┆ 007050040 ┆ 2014.0    ┆ -2.1475e9 ┆ … ┆ 01        ┆ 00        ┆ N         ┆ 2.0      │
│ 25%       ┆ null      ┆ 2018.0    ┆ 221131.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ 18.0     │
│ 50%       ┆ null      ┆ 2019.0    ┆ 761061.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ 25.0     │
│ 75%       ┆ null      ┆ 2020.0    ┆ 2.713805e ┆ … ┆ null      ┆ null      ┆ null      ┆ 35.0     │
│           ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 998591507 ┆ 2022.0    ┆ 2.1475e9  ┆ … ┆ 97        ┆ 53        ┆ O         ┆ 55.0     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [42]:
# mets moi tout la db dans un parquet 

output_filepath = "../Data/processed/sirene_final.parquet"

df_final.write_parquet(output_filepath)

In [43]:
# mets moi le df_final dans un csv  

output_csv_filepath = "../Data/processed/sirene_final.csv"

df_final.write_csv(output_csv_filepath)

In [35]:
df_final.schema

Schema([('siren', String),
        ('AnneeClotureExercice', Int32),
        ('DL_DettesCourtTerme', Int32),
        ('HN_RésultatNet', Int32),
        ('FR_ResultatExceptionnel', Int32),
        ('DA_TresorerieActive', Int32),
        ('CJCK_TotalActifBrut', Int32),
        ('FJ_ResultatFinancier', Int32),
        ('ratio_rentabilite_nette', Float64),
        ('ratio_endettement', Float64),
        ('ratio_tresorerie', Float64),
        ('ratio_resultat_financier', Float64),
        ('ratio_resultat_exceptionnel', Float64),
        ('variation_resultat_net_N-1', Int32),
        ('variation_resultat_net_N-2', Int32),
        ('Y_RN', Int32),
        ('dateCreationUniteLegale', Date),
        ('categorieJuridiqueUniteLegale', Int64),
        ('trancheEffectifsUniteLegale', String),
        ('activitePrincipaleUniteLegale', String),
        ('categorieEntreprise', String),
        ('departement', String),
        ('trancheEffectifsSiege', String),
        ('caractereEmployeurSiege', String),
        ('anciennete', Int32)])

In [39]:
import polars as pl
import pyarrow.parquet as pq
import sys

filepath = "../Data/processed/sirene_final2.parquet" 

print("--- Début de la lecture 'bypass' ---")

try:
    print(f"Lecture du fichier via PyArrow : {filepath}")
    table_arrow = pq.read_table(
        filepath,
    )
    
    print("Conversion de la table PyArrow en DataFrame Polars...")
    df_final2 = pl.from_arrow(table_arrow)
    
    print("--- SUCCÈS ! ---\n")
    print("Le DataFrame est maintenant dans Polars, prêt pour la transformation.")
    print(df_final2.head())

except Exception as e:
    print(f"\n--- ERREUR ---", file=sys.stderr)
    print(f"Impossible de lire le fichier, même avec PyArrow : {e}", file=sys.stderr)

--- Début de la lecture 'bypass' ---
Lecture du fichier via PyArrow : ../Data/processed/sirene_final2.parquet
Conversion de la table PyArrow en DataFrame Polars...
--- SUCCÈS ! ---

Le DataFrame est maintenant dans Polars, prêt pour la transformation.
shape: (5, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ siren     ┆ AnneeClot ┆ DL_Dettes ┆ HN_Résult ┆ … ┆ departeme ┆ trancheEf ┆ caractere ┆ ancienne │
│ ---       ┆ ureExerci ┆ CourtTerm ┆ atNet     ┆   ┆ nt        ┆ fectifsSi ┆ Employeur ┆ te       │
│ str       ┆ ce        ┆ e         ┆ ---       ┆   ┆ ---       ┆ ege       ┆ Siege     ┆ ---      │
│           ┆ ---       ┆ ---       ┆ i32       ┆   ┆ str       ┆ ---       ┆ ---       ┆ i32      │
│           ┆ i32       ┆ i32       ┆           ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 007050040 ┆ 2018      ┆ 7822201   ┆ 557967    ┆ … ┆ 04        ┆ 22        ┆ O         ┆ 55       │
│ 007050040 ┆ 2019      ┆ 7509642   ┆ 260111    ┆ … ┆ 04        ┆ 22        ┆ O         ┆ 55       │
│ 007050040 ┆ 2020      ┆ 8042649   ┆ 542798    ┆ … ┆ 04        ┆ 22        ┆ O         ┆ 55       │
│ 007050040 ┆ 2021      ┆ 8327563   ┆ 720752    ┆ … ┆ 04        ┆ 22        ┆ O         ┆ 55       │
│ 007050073 ┆ 2018      ┆ 2620977   ┆ 329022    ┆ … ┆ 04        ┆ 01        ┆ O         ┆ 55       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [40]:
df_final2.describe()

shape: (9, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ siren     ┆ AnneeClot ┆ DL_Dettes ┆ … ┆ departeme ┆ trancheEf ┆ caractere ┆ ancienne │
│ ---       ┆ ---       ┆ ureExerci ┆ CourtTerm ┆   ┆ nt        ┆ fectifsSi ┆ Employeur ┆ te       │
│ str       ┆ str       ┆ ce        ┆ e         ┆   ┆ ---       ┆ ege       ┆ Siege     ┆ ---      │
│           ┆           ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 207320    ┆ 207320.0  ┆ 207320.0  ┆ … ┆ 207320    ┆ 207320    ┆ 207320    ┆ 207320.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 2019.5013 ┆ 8.4845e6  ┆ … ┆ null      ┆ null      ┆ null      ┆ 26.81118 │
│           ┆           ┆ 41        ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ std       ┆ null      ┆ 1.229138  ┆ 7.5514e7  ┆ … ┆ null      ┆ null      ┆ null      ┆ 11.37399 │
│ min       ┆ 007050040 ┆ 2014.0    ┆ -2.1475e9 ┆ … ┆ 01        ┆ 00        ┆ N         ┆ 2.0      │
│ 25%       ┆ null      ┆ 2018.0    ┆ 222525.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ 18.0     │
│ 50%       ┆ null      ┆ 2020.0    ┆ 763032.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ 25.0     │
│ 75%       ┆ null      ┆ 2021.0    ┆ 2.710781e ┆ … ┆ null      ┆ null      ┆ null      ┆ 35.0     │
│           ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 998591507 ┆ 2022.0    ┆ 2.1475e9  ┆ … ┆ 97        ┆ 53        ┆ O         ┆ 55.0     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [47]:
df_final2.schema

Schema([('siren', String),
        ('AnneeClotureExercice', Int32),
        ('DL_DettesCourtTerme', Int32),
        ('HN_RésultatNet', Int32),
        ('FR_ResultatExceptionnel', Int32),
        ('DA_TresorerieActive', Int32),
        ('CJCK_TotalActifBrut', Int32),
        ('FJ_ResultatFinancier', Int32),
        ('ratio_rentabilite_nette', Float64),
        ('ratio_endettement', Float64),
        ('ratio_tresorerie', Float64),
        ('ratio_resultat_financier', Float64),
        ('ratio_resultat_exceptionnel', Float64),
        ('variation_resultat_net_N-1', Int32),
        ('variation_resultat_net_N-2', Int32),
        ('Y_RN', Int32),
        ('dateCreationUniteLegale', Date),
        ('categorieJuridiqueUniteLegale', Int64),
        ('trancheEffectifsUniteLegale', String),
        ('activitePrincipaleUniteLegale', String),
        ('categorieEntreprise', String),
        ('departement', String),
        ('trancheEffectifsSiege', String),
        ('caractereEmployeurSiege', String),
        ('anciennete', Int32)])

---

Fichier pour test

In [50]:
import pandas as pd
import polars as pl
import os

# Charger avec Polars (plus rapide)
print("📂 Chargement du fichier Parquet...")
df_pl = pl.read_parquet('../Data/processed/sirene_final2.parquet')
df = df_pl.to_pandas()

print(f"✅ Chargé : {len(df):,} lignes")

# Split temporel (80/20 comme votre pipeline)
print("\n📊 Split temporel 80/20...")
df_sorted = df.sort_values(by='AnneeClotureExercice').reset_index(drop=True)
split_point = int(len(df_sorted) * 0.8)
df_test = df_sorted.iloc[split_point:].copy()

print(f"Test set : {len(df_test):,} lignes")

# Échantillon stratifié optimisé
print("\n🎯 Création de l'échantillon stratifié...")

# 1. TOUTES les pertes (crucial pour comprendre R²=-2.18)
pertes = df_test[df_test['Y_RN'] <= 0].copy()
print(f"  ✓ Pertes : {len(pertes):,} lignes")

# 2. Échantillon de profits (limité à 5000 pour taille fichier)
profits = df_test[df_test['Y_RN'] > 0].copy()
nb_profits = min(5000, len(profits))
profits_sample = profits.sample(nb_profits, random_state=42)
print(f"  ✓ Profits : {len(profits_sample):,} lignes")

# 3. Valeurs extrêmes (pour comprendre les outliers)
extremes_pos = df_test.nlargest(500, 'Y_RN')
extremes_neg = df_test.nsmallest(500, 'Y_RN')
print(f"  ✓ Extrêmes : 1,000 lignes")

# Combiner et dédupliquer
sample = pd.concat([pertes, profits_sample, extremes_pos, extremes_neg]).drop_duplicates()
print(f"\n✅ Total après déduplication : {len(sample):,} lignes")

# Colonnes à garder (TOUTES les colonnes utiles pour l'analyse)
cols_a_garder = [
    # Target
    'Y_RN',
    
    # Colonnes financières brutes (importantes !)
    'HN_RésultatNet',
    'CJCK_TotalActifBrut', 
    'DL_DettesCourtTerme',
    'DA_TresorerieActive',
    'FR_ResultatExceptionnel',
    'FJ_ResultatFinancier',
    
    # Ratios calculés
    'ratio_rentabilite_nette',
    'ratio_endettement',
    'ratio_tresorerie',
    'ratio_resultat_financier',
    'ratio_resultat_exceptionnel',
    
    # Variations temporelles
    'variation_resultat_net_N-1',
    'variation_resultat_net_N-2',
    
    # Métadonnées temporelles et géographiques
    'AnneeClotureExercice',
    'anciennete',
    'departement',
    
    # Catégorielles importantes
    'activitePrincipaleUniteLegale',
    'categorieEntreprise',
    'trancheEffectifsUniteLegale',
    'categorieJuridiqueUniteLegale',
]

sample_final = sample[cols_a_garder].copy()

# Sauvegarder
output_file = '../Data/processed/sample_analyse.csv'
sample_final.to_csv(output_file, index=False)

# Statistiques
taille_mb = os.path.getsize(output_file) / (1024 * 1024)
print(f"\n📁 Fichier créé : '{output_file}'")
print(f"   📏 Taille : {taille_mb:.2f} MB")
print(f"   📊 Lignes : {len(sample_final):,}")
print(f"   🔢 Colonnes : {len(sample_final.columns)}")

# Distribution Y_RN
print("\n📊 Distribution Y_RN dans l'échantillon:")
print(f"   Min      : {sample_final['Y_RN'].min():>15,} €")
print(f"   Q25      : {sample_final['Y_RN'].quantile(0.25):>15,.0f} €")
print(f"   Médiane  : {sample_final['Y_RN'].median():>15,.0f} €")
print(f"   Q75      : {sample_final['Y_RN'].quantile(0.75):>15,.0f} €")
print(f"   Max      : {sample_final['Y_RN'].max():>15,} €")
print(f"\n   Profits  : {(sample_final['Y_RN'] > 0).sum():>6,} ({(sample_final['Y_RN'] > 0).mean()*100:>5.1f}%)")
print(f"   Pertes   : {(sample_final['Y_RN'] <= 0).sum():>6,} ({(sample_final['Y_RN'] <= 0).mean()*100:>5.1f}%)")

# Aperçu
print("\n👀 Aperçu des premières lignes:")
print(sample_final.head())

print("\n✅ Prêt à uploader ! Utilisez le bouton 📎 pour envoyer 'sample_analyse.csv'")

📂 Chargement du fichier Parquet...
✅ Chargé : 207,320 lignes

📊 Split temporel 80/20...
Test set : 41,464 lignes

🎯 Création de l'échantillon stratifié...
  ✓ Pertes : 7,463 lignes
  ✓ Profits : 5,000 lignes
  ✓ Extrêmes : 1,000 lignes

✅ Total après déduplication : 12,900 lignes

📁 Fichier créé : '../Data/processed/sample_analyse.csv'
   📏 Taille : 2.25 MB
   📊 Lignes : 12,900
   🔢 Colonnes : 21

📊 Distribution Y_RN dans l'échantillon:
   Min      :    -790,850,871 €
   Q25      :        -138,106 €
   Médiane  :         -10,710 €
   Q75      :         146,067 €
   Max      :   2,147,483,647 €

   Profits  :  5,437 ( 42.1%)
   Pertes   :  7,463 ( 57.9%)

👀 Aperçu des premières lignes:
          Y_RN  HN_RésultatNet  CJCK_TotalActifBrut  DL_DettesCourtTerme  \
165858 -119630          -42481               169159               400958
165863  -52536           29447              1090934               620921
165864  -91605          565549              8466115             12895042
165866  -13991           23119               709504               280400
165889 -163253         -155586               813311                 3523

        DA_TresorerieActive  FR_ResultatExceptionnel  FJ_ResultatFinancier  \
165858                 8000                   567826                365739
165863                40000                  2460608               2462507
165864               974400                   761080                745832
165866                 8000                  1134880               1097535
165889                60000                  1022694               1027644

        ratio_rentabilite_nette  ratio_endettement  ratio_tresorerie  ...  \
165858            -1.161511e-01           2.370302          0.047293  ...
165863             2.944700e+10           0.569165          0.036666  ...
165864             5.655490e+11           1.523136          0.115094  ...
165866             2.384198e-02           0.395206          0.011275  ...
165889            -1.555860e+11           0.004332          0.073773  ...

        ratio_resultat_exceptionnel  variation_resultat_net_N-1  \
165858                 1.552544e+00                        7471
165863                 2.460608e+12                      -17630
165864                 7.610800e+11                      345087
165866                 1.170370e+00                       19454
165889                 1.022694e+12                       46797

        variation_resultat_net_N-2  AnneeClotureExercice  anciennete  \
165858                      -45195                  2021          32
165863                      100180                  2021          32
165864                      409566                  2021          32
165866                       17585                  2021          32
165889                      -39891                  2021          32

        departement activitePrincipaleUniteLegale categorieEntreprise  \
165858           75                        56.10A                 PME
165863           69                        25.62B                 PME
165864           62                        66.30Z                 ETI
165866           64                        46.44Z                 PME
165889           37                        14.14Z                 PME

       trancheEffectifsUniteLegale categorieJuridiqueUniteLegale
165858                          03                          5499
165863                          11                          5710
165864                          01                          5710
165866                          02                          5499
165889                          02                          5499

[5 rows x 21 columns]

✅ Prêt à uploader ! Utilisez le bouton 📎 pour envoyer 'sample_analyse.csv'

In [54]:
import pandas as pd

df = pd.read_csv('../Data/processed/sample_analyse.csv')

# Prendre 50 pertes + 50 profits
pertes_sample = df[df['Y_RN'] <= 0].head(50)
profits_sample = df[df['Y_RN'] > 0].head(50)
mini_sample = pd.concat([pertes_sample, profits_sample])

# Afficher en format copiable
print(mini_sample.to_csv(index=False))

Y_RN,HN_RésultatNet,CJCK_TotalActifBrut,DL_DettesCourtTerme,DA_TresorerieActive,FR_ResultatExceptionnel,FJ_ResultatFinancier,ratio_rentabilite_nette,ratio_endettement,ratio_tresorerie,ratio_resultat_financier,ratio_resultat_exceptionnel,variation_resultat_net_N-1,variation_resultat_net_N-2,AnneeClotureExercice,anciennete,departement,activitePrincipaleUniteLegale,categorieEntreprise,trancheEffectifsUniteLegale,categorieJuridiqueUniteLegale
-119630,-42481,169159,400958,8000,567826,365739,-0.1161511350987558,2.370302496453808,0.0472927837120857,0.9999999999972656,1.5525443007129331,7471,-45195,2021,32,75,56.10A,PME,3,5499
-52536,29447,1090934,620921,40000,2460608,2462507,29447000000.0,0.5691645874080657,0.0366658294635269,2462507000000.0,2460608000000.0,-17630,100180,2021,32,69,25.62B,PME,11,5710
-91605,565549,8466115,12895042,974400,761080,745832,565549000000.0,1.5231357003771475,0.115094113415644,745832000000.0,761080000000.0,345087,409566,2021,32,62,66.30Z,ETI,1,5710
-13991,23119,709504,280400,8000,1134880,1097535,0.0238419843328866,0.3952056648018965,0.0112754825906389,1.1318574451660846,1.1703703092567308,19454,17585,2021,32,64,46.44Z,PME,2,5499
-163253,-155586,813311,3523,60000,1022694,1027644,-155586000000.0,0.0043316763206149,0.073772517523956,1027644000000.0,1022694000000.0,46797,-39891,2021,32,37,14.14Z,PME,2,5499
-18744,1908,1271975,816471,221952,10391769,10375478,0.0001861918812727,0.6418923327890549,0.1744939955579516,1.0124893961868515,1.014079150871241,-12781,-10099,2021,32,1,46.23Z,PME,1,5532
-134410,-215746,931814,50304,30000,1454996,949569,-0.2364021068938253,0.0539850227619954,0.0321952664372587,1.0404833101937596,1.5943012613076877,292014,-64700,2021,32,69,46.49Z,PME,2,5499
-2577507,-5799381,3257765,-4602112,1133920,13551896,12487028,-0.947657108905766,-1.41265929248997,0.3480668495117517,2.0404627413348684,2.2144691965490138,573692,-3481166,2021,32,75,47.29Z,GE,22,5202
-230900,-248821,311201,-353487,37000,1888306,1707018,-248821000000.0,-1.1358800260888111,0.1188942194912005,1707018000000.0,1888306000000.0,-358829,302616,2021,32,17,87.10A,GE,12,5710
-60495,-687143,9159136,-2016368,500000,15831237,15225525,-0.4154386469794068,-0.2201482759945676,0.0545903019673411,9.205174913447614,9.571381327162358,1700224,1452609,2021,32,92,33.12Z,PME,22,5710
-76340,-83756,3165993,1365422,1952700,7900733,7936367,-83756000000.0,0.4312776433806293,0.6167733156704337,7936367000000.0,7900733000000.0,351192,-106305,2021,32,30,81.30Z,ETI,22,5599
-207526,-88787,1259435,191766,40000,10204903,10158389,-0.0088577054665024,0.1522635149887431,0.0317602734559292,1.0134368519733514,1.0180772532941404,-265038,-171705,2021,32,58,47.11D,PME,12,5710
-32812,12696,3673388,-167399,573680,13558882,12152060,0.0012984002044549,-0.04557073742277,0.1561719045197087,1.2427723053362305,1.386645806630474,246601,605979,2021,32,50,63.11Z,ETI,12,5710
-17720,-96420,1448250,1952759,1558458,15662,14546,-96420000000.0,1.3483576730527544,1.0760973588806657,14546000000.0,15662000000.0,-393690,-271188,2021,32,29,64.30Z,PME,1,5710
-121051,89113,877369,869832,15200,1678583,1658642,89113000000.0,0.9914095437598188,0.0173245236610624,1658642000000.0,1678583000000.0,-135409,88419,2021,32,94,81.21Z,PME,21,5710
-421,-22801,225636,-223448,10000,438196,363322,-22801000000.0,-0.9903029658343956,0.0443191689267478,363322000000.0,438196000000.0,84653,-37975,2021,32,69,85.59A,PME,2,5499
-136610,-161528,411777,193182,16000,905997,726209,-137.94022191465393,0.4691422784651179,0.0388559827284213,620.1613999827827,773.6951317047864,-16479,-113063,2021,32,38,26.12Z,PME,3,5499
-448782,-134830,15914660,655678,400000,23630755,8111286,-0.0167820090092345,0.0411996234917967,0.0251340587860485,1.0095948581805094,2.9412708099459643,-93007,164484,2021,32,67,46.74A,PME,12,5499
-104546,68396,1834853,1897357,140512,11733801,11675735,0.0062741802840694,1.034064854241166,0.0765794317037514,1.071051908576813,1.0763784854581335,67405,-62256,2021,32,31,47.11D,PME,11,5710
-55280,128581,786754,532100,7622,1502950,0,128581000000.0,0.6763232217431671,0.0096879075288976,0.0,1502950000000.0,70522,45902,2021,32,90,47.22Z,PME,3,5499
-19858,-34021,8650501,1293569,240000,25662199,25267843,-0.001460473690417,0.1495368880946722,0.0277440578297109,1.0847129689041544,1.1016421174494089,369316,-23272,2021,32,61,45.11Z,ETI,12,5710
-19082,5386,44630,69982,7622,197497,196269,0.0274419291888813,1.5680483979034718,0.1707819852079143,0.999999999994905,1.0062567190895848,108,2767,2021,32,6,10.71D,PME,1,5710
-1309694,-279849,8118178,-249305,7622,10255609,10064306,-0.0384906706725846,-0.0307094769294254,0.00093888062075,1.3842532501245934,1.410565228268798,-328445,-277014,2021,32,41,46.75Z,GE,21,5710
-18743632,-9671199,22323088,20776697,31579526,104238761,94005950,-0.1159731909939488,0.9307268331334388,1.4146575957590897,1.1272821491851843,1.2499899690230332,10055724,-7480897,2021,32,13,56.10B,ETI,42,5710
-166946,-117344,1853279,704529,163417,3840864,3783831,-0.0677504991333337,0.3801526915265428,0.0881772253394722,2.1846574080155885,2.217586353825101,-54929,-227596,2021,32,97,96.03Z,PME,12,5560
-753445,-65989,3452317,-2104638,30000,10843753,10663758,-65989000000.0,-0.6096305756393142,0.0086898161437641,10663758000000.0,10843753000000.0,-56611,-13310,2021,32,76,52.24A,ETI,32,5499
-7296247,-753730,17107466,7019798,1530000,41396038,40602180,-3.2976182142587867,0.4103353471519154,0.0894346363160921,177.6372020572537,181.1103829049512,-720373,-2680560,2021,32,21,24.42Z,ETI,12,5710
-24049,93753,2812654,173597,100000,1491142,734611,93753000000.0,0.0617199982649619,0.0355536087979411,734611000000.0,1491142000000.0,1228075,-810328,2021,33,69,79.12Z,PME,12,5710
-959,1240,762058,602717,300000,1531050,1500398,0.0026939186957898,0.7909069913303306,0.3936708229552164,3.25963727687562,3.3262292090234844,-1781,1145,2021,34,78,96.03Z,PME,11,5499
-278648,-121000,1634950,2056536,176000,2422982,2253989,-121000000000.0,1.2578586501108548,0.1076485519434186,2253989000000.0,2422982000000.0,-129623,-241364,2021,35,37,10.61A,PME,11,5499
-12724,17975,83891,145689,7622,195891,154231,17975000000.0,1.7366463625211688,0.090855991702437,154231000000.0,195891000000.0,11092,18698,2021,35,89,56.10A,PME,2,5499
-37809,-35814,278658,719365,304898,15637,15631,-60.59898466903725,2.5815336362043024,1.0941656080173756,26.448392510239607,26.45854479448639,-3002,-7783,2021,35,59,64.20Z,PME,1,5710
-1063055,-768066,11155787,5282078,2166000,31726242,0,-768066000000.0,0.4734832244466057,0.1941593183878291,0.0,31726242000000.0,156321,-64,2021,35,69,46.69B,ETI,22,5710
-46944,-294971,1154116,205877,181291,887112,355943,-294971000000.0,0.1783850150243317,0.1570821303923028,355943000000.0,887112000000.0,-147927,-251418,2021,35,38,82.30Z,PME,12,5710
-326687,-514832,3258069,810535,3400000,10065986,10106169,-0.0993626747664795,0.2487777269295866,1.0435629202447698,1.950492555789224,1.9427372290804303,-511881,-898826,2021,35,40,47.29Z,ETI,12,5710
-12449,155518,720532,226820,44640,791897,166306,155518000000.0,0.314795179117215,0.0619542227131314,166306000000.0,791897000000.0,166996,174286,2021,35,17,79.11Z,PME,2,5499
-223537,-217818,1654570,159056,127280,3377576,3202445,-1523.2027865510297,0.0961313211286943,0.0769263313126208,22394.72012311385,23619.412422241872,420951,137910,2021,35,81,16.24Z,ETI,11,5710
-20494,3780,2103270,1474373,216000,1693881,819596,0.0046225300647831,0.7009908380756152,0.1026972286011293,1.002277024067726,2.071432764197072,-45284,137,2021,35,91,46.62Z,PME,3,5710
-133194,-312964,104110,-2905208,37000,1266026,1218913,-312964000000.0,-27.90517721613769,0.355393333970268,1218913000000.0,1266026000000.0,-88975,1715,2021,35,59,87.10A,GE,12,5710
-22559,-30306,69884,-71030,7622,266754,229725,-1.0787740717944407,-1.0163986033853758,0.109066452977662,8.177303954430737,9.49539031041557,-44710,-68565,2021,35,21,96.02A,ETI,3,5499
-336600,52560,3520177,4799019,2299000,34147698,18283710,52560000000.0,1.363289118700178,0.6530921598542764,18283710000000.0,34147698000000.0,-863719,357392,2021,35,51,10.61B,GE,21,5710
-3577176,-4167722,5849989,-4391878,313800,37313938,34942794,-4167722000000.0,-0.7507497877345153,0.0536411265046731,34942794000000.0,37313938000000.0,-3526612,-4834894,2021,35,6,66.22Z,ETI,22,5710
-2434688,-3384781,4241396,4156178,18590896,7990948,0,-3384781000000.0,0.9799080302803652,4.383202134390568,0.0,7990948000000.0,106596,77734,2021,35,31,46.69B,PME,21,5710
-20925,-25102,172860,198280,76225,0,0,-25102000000.0,1.147055420564925,0.440963785719999,0.0,0.0,-4469,4271,2021,35,83,11.05Z,PME,1,5499
-6258117,-133154,63624857,20874012,10720096,288107023,235684981,-12.171297987918528,0.328079511439997,0.1684891173900765,21543.41690845124,26335.194056093675,3096415,-673669,2021,35,62,10.20Z,ETI,32,5710
-5448654,-4583514,13002351,-7640442,26400000,54368102,1554993,-4583514000000.0,-0.5876200388683103,2.0304020403693124,1554993000000.0,54368102000000.0,-3367996,-2090053,2021,35,38,70.10Z,PME,12,5710
-701299,-1392574,4848832,1719638,4589526,10058955,8271327,-1392574000000.0,0.354649944563896,0.9465219665270014,8271327000000.0,10058955000000.0,134573,-1063600,2021,35,73,49.39A,GE,22,5599
-1035931,-357084,35718863,3357573,8500000,25160779,21995466,-357084000000.0,0.0939999965844351,0.2379695008768829,21995466000000.0,25160779000000.0,5214606,-1893862,2021,35,77,63.11Z,ETI,22,5710
-48901,30979,111640,124766,7622,1072208,1072208,0.0288927148463461,1.117574346102494,0.0682730204221759,0.9999999999990672,0.9999999999990672,-13,29442,2021,35,91,47.22Z,PME,2,5499
-19073,25005,1207347,97394,7622,443620,443540,0.500099999989998,0.0806677781946029,0.0063130152309101,8.870799999822584,8.872399999822552,60202,7558,2021,35,75,68.31Z,PME,11,5710
153734,133277,382515,320399,7501,472555,463528,479.4136673402386,0.8376115969286495,0.019609688508896,1667.3669004770975,1699.8381233818773,10045,29060,2021,22,83,62.01Z,PME,2,5710
432219,1882285,12663307,58590125,11625000,137467211,2191828,8.84640510584542,4.626763372316202,0.9180066470787672,10.301202214507876,646.07147019539,-728991,-536644,2021,20,56,64.20Z,ETI,11,5499
280055,135958,5022789,5135981,106074,3536635,0,135958000000.0,1.0225356868462874,0.0211185458915313,0.0,3536635000000.0,-24465,-143823,2021,34,76,28.25Z,PME,12,5710
292690,275866,1306871,503746,50000,2258093,2229082,0.3367151397676309,0.385459620727382,0.0382593232231503,2.7207617364354806,2.756171837425812,81732,106309,2021,27,38,46.51Z,PME,11,5710
14770,34958,7902374,1528627,902200,12957609,12420912,0.0028144471195027,0.1934389589761009,0.1141682233718482,0.9999999999999196,1.0432091459949926,27750,-27441,2021,37,13,29.20Z,PME,11,5599
142103,66126,562760,828975,130334,261752,261750,66126000000.0,1.4730524557511673,0.2315978392205707,261750000000.0,261752000000.0,-315230,9450,2021,42,14,68.20B,PME,1,5710
288135,366587,1054681,374972,7622,3392259,3187768,366587000000.0,0.355531198532679,0.0072268297238622,3187768000000.0,3392259000000.0,178528,199224,2021,28,1,56.10C,PME,21,5710
124116,167477,1060793,311775,40000,2166562,2118938,167477000000.0,0.2939074824208927,0.0377076394734526,2118938000000.0,2166562000000.0,9557,74381,2021,42,75,81.29A,PME,12,5710
29743,55611,536520,64102,7622,1393402,1384362,55611000000.0,0.119477372697906,0.0142063669574028,1384362000000.0,1393402000000.0,1279,-281,2021,24,75,41.20A,PME,2,5499
1314013,892462,5155499,1352859,7500,6095531,0,892462000000.0,0.262410874291652,0.0014547573377472,0.0,6095531000000.0,-131492,-103993,2021,31,97,43.29B,ETI,12,5499
774373,881105,23612663,12548151,1000400,37810334,36738923,0.0278502917657883,0.5314161727544017,0.0423670976882174,1.1612574264257165,1.195122980418799,96093,137938,2021,54,38,45.11Z,ETI,21,5710
74830,92330,491286,351548,100000,1356943,1350158,92330000000.0,0.7155668999305587,0.2035474245140233,1350158000000.0,1356943000000.0,30978,31616,2021,19,51,26.11Z,PME,3,5710
1944624,1528848,40685882,3969881,127500,100402876,0,1528848000000.0,0.0975739201131218,0.0031337651719089,0.0,100402876000000.0,831711,966029,2021,16,60,45.31Z,ETI,3,5710
186405,128977,747548,484908,26432,363605,363604,128977000000.0,0.6486647011286918,0.0353582646197496,363604000000.0,363605000000.0,-379030,58967,2021,29,75,66.19B,PME,2,5710
1220064,-42820,10155101,3420502,4050000,26540038,23709994,-42820000000.0,0.3368259951328562,0.3988143495568976,23709994000000.0,26540038000000.0,2175419,-299869,2021,30,75,73.20Z,ETI,22,5710
137352,483593,14780393,2216502,639165,31007315,27762473,483593000000.0,0.1499623183226488,0.0432441140096854,27762473000000.0,31007315000000.0,1279207,137045,2021,20,69,42.11Z,GE,22,5710
2016556,1768908,8355397,1926386,42400,10852455,0,1768908000000.0,0.2305558910007231,0.0050745643803633,0.0,10852455000000.0,543065,676385,2021,34,91,71.12B,PME,21,5710
6921051,45301246,170807831,694613739,445511568,71273325,26863340,171.64894398952836,4.066638718689636,2.6082619596053376,101.78669132040336,270.0585977452464,22993172,-12845164,2021,39,78,26.11Z,ETI,32,5710
1276465,2127193,3120930,11848267,7400000,1520658,1514493,2127193000000.0,3.79638985815004,2.3710881051473853,1514493000000.0,1520658000000.0,498394,998954,2021,16,76,70.10Z,PME,3,5710
15593291,3412082,149917588,8427960,3250000,332900901,165822459,3412082000000.0,0.0562172865267812,0.0216785771660092,165822459000000.0,332900901000000.0,-2626441,-1473114,2021,49,69,70.10Z,GE,42,5710
1147565,501670,890196,815994,200000,5401627,5401605,0.0929142404172236,0.9166453230514215,0.2246696233186571,1.000430612970433,1.0004346875877894,66535,78557,2021,17,62,46.69B,PME,1,5499
15636,9898,152820,616947,436000,136837,79150,9898000000.0,4.037082842533457,2.853029708134714,79150000000.0,136837000000.0,13700,-6890,2021,16,43,64.20Z,PME,1,5499
97396,119059,412676,165294,40000,455109,370102,119059000000.0,0.4005418294245351,0.0969283408773543,370102000000.0,455109000000.0,32832,42150,2021,31,69,56.10A,PME,3,5499
2084887,-9632,2155872,8770945,5692000,104600,95600,-9632000000.0,4.068397845510277,2.6402309599073415,95600000000.0,104600000000.0,-18370,-369959,2021,16,75,64.20Z,PME,1,5499
1316,1349,46580,11991,7500,82117,0,1349000000.0,0.257428080715813,0.1610133104302058,0.0,82117000000.0,-1042,-1598,2021,39,92,46.13Z,PME,1,5499
184125,128831,726322,200000,200000,2302805,2229856,128831000000.0,0.2753599643129695,0.2753599643129695,2229856000000.0,2302805000000.0,320405,424530,2021,16,21,42.12Z,PME,11,5202
21890,66036,385158,273078,16000,463815,464506,66036000000.0,0.7090025392158309,0.0415413934020803,464506000000.0,463815000000.0,61109,18963,2022,24,70,43.12A,PME,2,5499
5492336,3402186,51243624,35826606,1500000,84183968,74995670,25.97723107914928,0.6991427070029103,0.0292719343971451,572.625908614527,642.7827255463718,-370940,-463160,2021,30,71,49.41C,ETI,41,5710
4919709,4172150,35350753,21196726,200000,15477521,15433954,4172150000000.0,0.5996117253852953,0.0056575881141766,15433954000000.0,15477521000000.0,-3857790,-1181098,2021,46,68,52.29B,ETI,12,5710
1621,7894,287040,157443,11648,488714,0,7894000000.0,0.5485054347806978,0.0405797101447861,0.0,488714000000.0,-1059,-14422,2021,20,97,10.89Z,PME,2,5710
83922,26510,1084566,547371,200000,2818795,2809838,26510000000.0,0.5046912774321667,0.1844055594586365,2809838000000.0,2818795000000.0,-43391,-39355,2022,26,91,43.99A,ETI,11,5710
1184,283,321026,14694,9000,378151,0,283000000.0,0.0457719935455515,0.0280351124207134,0.0,378151000000.0,24743,150,2021,29,66,46.34Z,PME,1,5499
89963,182012,3454958,10248579,1549187,44619,36736,182.011999817988,2.966339677645006,0.4483953205797441,36.735999963264,44.618999955381,605088,-29053,2021,37,69,68.10Z,PME,2,5710
13919903,5052842,278466697,9358405,3611142,299228945,296020423,5052842000000.0,0.033606909195321,0.012967949269711,296020423000000.0,299228945000000.0,4123994,-1405934,2021,26,94,41.20B,GE,42,5710
538104,411590,4106456,1720502,100000,12194338,11654996,0.0353180209345846,0.4189749019591543,0.0243518985714142,1.0001005678478585,1.0463808274433313,337511,304475,2021,27,92,46.49Z,PME,11,5499
867862,1076523,4668490,2095019,80000,43601313,43494377,0.0253903568989485,0.4487573069663962,0.017136161799636,1.0258375855670705,1.0283597269475573,-94508,176604,2021,43,60,47.11F,PME,22,5710
111063,180313,702693,387312,2000,2442571,2252623,180313000000.0,0.5511823797866904,0.0028461931455089,2252623000000.0,2442571000000.0,85056,-78310,2021,18,50,56.10C,PME,21,5710
11442,9423,536681,78274,31400,595062,0,9423000000.0,0.1458482785860765,0.0585077541406189,0.0,595062000000.0,-5938,9127,2021,16,75,70.22Z,PME,2,5710
1288885,1255266,10395414,3131216,100000,21224161,7685591,1255266000000.0,0.3012112841296843,0.0096196265006848,7685591000000.0,21224161000000.0,-803158,924671,2021,46,60,22.21Z,PME,12,5710
35337,82004,272044,159111,7622,395524,323431,82004000000.0,0.5848723000669566,0.0280175265764802,323431000000.0,395524000000.0,70827,119784,2021,20,75,56.10A,PME,3,5499
255679,347851,2723742,693941,40000,6344420,6228411,0.0566183088940122,0.2547748648733049,0.0146856787463663,1.013773419989776,1.0326557385586042,168736,268096,2021,22,74,47.64Z,PME,11,5499
879177,1053089,3492107,4727450,500000,8570179,5196033,12.87001527634745,1.3537529061963585,0.1431800342887136,63.501778184375176,104.73790406227025,475059,243206,2021,36,38,18.12Z,PME,21,5710
199442,261418,668830,444940,54000,1471714,1256091,261418000000.0,0.6652512596614009,0.0807380051730922,1256091000000.0,1471714000000.0,74692,192120,2021,27,92,50.30Z,PME,11,5710
5103196,3844253,41330210,15718239,1009000,49415069,0,3844253000000.0,0.380308713650369,0.0244131350893202,0.0,49415069000000.0,31568,77755,2021,30,92,66.22Z,ETI,22,5710
84580,382312,2160255,1890080,11475,2591979,2525726,235.26892293214215,0.8749337462471446,0.0053118729038908,1554.292922120435,1595.063999018422,173114,155850,2021,40,54,22.29A,PME,2,5710
543004,775310,5045085,2621998,1000000,11628659,11306572,775310000000.0,0.519713344770104,0.1982127159403264,11306572000000.0,11628659000000.0,289126,205876,2021,17,95,43.12A,ETI,21,5710
2131660,1243729,15221461,3821013,330000,29004764,28794980,0.135774436072153,0.2510280057873386,0.021679916270848,3.14346788666094,3.1663694225236245,501650,160417,2021,39,13,62.02A,GE,22,5710
451452,-378986,4360915,688572,684000,22698173,21667917,-130.28050872111362,0.1578962213204894,0.1568478174878077,7448.5792342906225,7802.740801717862,-41938,-734779,2021,34,76,49.41A,ETI,22,5710
585166,1083887,11768111,6538609,1000000,23881588,23784746,1083887000000.0,0.5556209488506222,0.084975405143605,23784746000000.0,23881588000000.0,468476,428479,2021,28,94,38.11Z,PME,12,5499
31597,6840,879459,429480,28000,1435891,1426696,0.006267214223272,0.488345676148077,0.0318377548014951,1.3072236057727025,1.3156486108579344,123658,18928,2021,41,2,43.32A,PME,11,5499